// Editorial lessons for ITPEC FE April 2026 Subject A. Original keys never change.
type Translation = [core:string, detail:string, search:string, next:string];
type Entry = [number:number, answerId:string, ru:Translation, en:Translation, ja:Translation];
export const feLessonEntries:Entry[] = [
  [1,'c',
    ['Префиксная запись: ^/−ab+cde. Сначала записывают оператор, затем его левое и правое подвыражения.',
     'Постройте дерево выражения ((a−b)/(c+d))^e. Последняя операция — возведение в степень, поэтому корень дерева — ^. Его левый аргумент — частное, правый — e. Частное записывается как / с аргументами −ab и +cd. Обход «корень → левое поддерево → правое поддерево» даёт ^ / − a b + c d e. Пробелы служат только для чтения. Скобки не нужны: у каждого из этих операторов ровно два аргумента. Важно не менять их местами: ^e/−ab+cd означало бы e в степени (a−b)/(c+d), а не исходное выражение. Для проверки восстановите скобки из префиксной записи и сравните структуру, а не только набор символов.',
     'префиксная польская запись дерево выражения прямой обход',
     'Сравните инфиксную, префиксную и постфиксную записи. Научитесь восстанавливать дерево и вычислять выражение стеком.'],
    ['The prefix form is ^/−ab+cde: write each operator before its left and right operands.',
     'Build the expression tree for ((a−b)/(c+d))^e. Exponentiation is performed last, so ^ is the root. Its left operand is the quotient and its right operand is e. The quotient is / followed by −ab and +cd. A root–left–right traversal gives ^ / − a b + c d e. Spaces only improve readability. Parentheses are unnecessary because each operator here takes exactly two operands. Operand order still matters: ^e/−ab+cd would mean e raised to the quotient, not the original expression. Check your answer by reconstructing its parentheses, rather than merely counting its symbols.',
     'prefix Polish notation expression tree preorder traversal',
     'Compare infix, prefix and postfix forms. Practise rebuilding expression trees and evaluating expressions with a stack.'],
    ['前置記法は ^/−ab+cde です。演算子、左の式、右の式の順に書きます。',
     '((a−b)/(c+d))^e の式木を考えます。最後に行う演算は累乗なので根は ^、左の子は商、右の子はeです。商は / の後に −ab と +cd を並べます。根→左部分木→右部分木の順にたどると ^ / − a b + c d e です。空白は読みやすさのためで、各演算子の引数が二つと分かるので括弧は不要です。ただし引数の順序は変えられません。^e/−ab+cd はeを商の値で累乗する別の式です。記号の数だけでなく、括弧付きの式へ戻して構造を確認しましょう。',
     '前置記法 ポーランド記法 式木 行きがけ順',
     '中置・前置・後置記法を比較し、式木の復元とスタックによる計算を練習しましょう。']],
  [2,'b',
    ['1234.2₈ = 668.25₁₀. Веса восьмеричных разрядов — степени 8, в том числе отрицательные после точки.',
     'В позиционной системе цифра умножается на основание в степени своего разряда. Слева от точки веса идут 8⁰, 8¹, 8², 8³ справа налево; справа от точки — 8⁻¹, 8⁻² и далее. Поэтому 1×512 + 2×64 + 3×8 + 4×1 + 2×(1/8) = 512 + 128 + 24 + 4 + 0.25 = 668.25. Дробная цифра 2 означает 2/8, а не 2/10. Обратная проверка: 668÷8 = 83 остаток 4; 83÷8 = 10 остаток 3; 10÷8 = 1 остаток 2; 1÷8 = 0 остаток 1. Читайте остатки снизу вверх: 1234. Для дроби 0.25×8 = 2.0, значит первая дробная цифра 2 и дальнейшего остатка нет.',
     'перевод восьмеричной в десятичную дроби обратный перевод системы счисления',
     'Освойте двоичную и шестнадцатеричную системы. Одна восьмеричная цифра соответствует 3 битам, шестнадцатеричная — 4; отдельно потренируйте дроби.'],
    ['1234.2₈ = 668.25₁₀. Octal place values are powers of 8, including negative powers after the point.',
     'Multiply each digit by its place value. Moving left from the point gives weights 8⁰, 8¹, 8², 8³; moving right gives 8⁻¹, 8⁻², and so on. Thus 1×512 + 2×64 + 3×8 + 4×1 + 2×(1/8) = 512 + 128 + 24 + 4 + 0.25 = 668.25. The fractional 2 means 2/8, not 2/10. Reverse check: divide 668, 83, 10 and 1 successively by 8; the remainders are 4, 3, 2 and 1. Read them backwards to obtain 1234. For the fraction, 0.25×8 = 2.0 gives the digit 2 with no remainder.',
     'octal to decimal fractional numbers decimal to octal conversion',
     'Study binary and hexadecimal too. Each octal digit represents 3 bits and each hexadecimal digit 4 bits. Practise fractional place values separately.'],
    ['1234.2₈ = 668.25₁₀ です。8進数の各桁の重みは8の累乗で、小数部では負の指数になります。',
     '各数字に桁の重みを掛けて合計します。小数点の左側は右から8⁰、8¹、8²、8³、右側は8⁻¹、8⁻²です。1×512 + 2×64 + 3×8 + 4×1 + 2×(1/8) = 512 + 128 + 24 + 4 + 0.25 = 668.25 となります。小数部の2は2/10ではなく2/8です。逆変換では668を8で割ると商83・余り4、83では商10・余り3、10では商1・余り2、1では商0・余り1です。余りを逆順に読むと1234になります。小数部は0.25×8 = 2.0なので数字2で終わります。',
     '8進数 10進数 相互変換 小数 基数変換',
     '2進数と16進数も学びましょう。8進数1桁は3ビット、16進数1桁は4ビットに対応します。小数の変換も練習しましょう。']],
  [3,'a',
    ['Это загрузка: ρ = λ/μ, где λ — интенсивность поступления, μ — интенсивность обслуживания.',
     'Для одного обслуживающего устройства сравнивают поступающую работу с его возможностями. Если приходит 8 заявок в час, а обслужить можно 10, то ρ = 8/10 = 0.8, или 80%. Единицы времени должны совпадать. Интервал между заявками — 1/λ, среднее время обслуживания — 1/μ; это длительности, а отношение λ/μ безразмерно. Среднее число заявок в системе — другая величина и учитывает также очередь. В простой устойчивой одноканальной модели нужно λ < μ; при приближении загрузки к 100% ожидание резко растёт. Для c одинаковых параллельных каналов, если μ задано на один канал, общая загрузка равна λ/(cμ).',
     'теория массового обслуживания коэффициент загрузки лямбда мю',
     'Изучите закон Литтла L = λW и модель M/M/1. Различайте время обслуживания, ожидание в очереди и полное время в системе.'],
    ['The ratio is utilization: ρ = λ/μ, with arrival rate λ and service rate μ.',
     'For one server, compare incoming demand with service capacity. With 8 arrivals per hour and capacity for 10, ρ = 8/10 = 0.8, or 80%. Both rates must use the same time unit. Mean inter-arrival time is 1/λ and mean service time is 1/μ: these are durations, whereas λ/μ is dimensionless. The mean number in the system is a different quantity that also includes the queue. A basic stable single-server model requires λ < μ; waiting grows sharply near full utilization. For c identical parallel servers, with μ specified per server, utilization is λ/(cμ).',
     'queueing theory utilization arrival rate service rate lambda mu',
     'Study Little’s law L = λW and M/M/1 queues. Distinguish service time, queueing delay and total time in the system.'],
    ['比率は利用率 ρ = λ/μ です。λは到着率、μはサービス率を表します。',
     '窓口が一つなら到着量を処理能力と比較します。毎時8件到着し毎時10件処理できる場合、ρ = 8/10 = 0.8、つまり80%です。時間の単位はそろえます。平均到着間隔は1/λ、平均サービス時間は1/μで、どちらも時間ですが、λ/μは無次元です。系内の平均件数は待ち行列も含む別の量です。基本的な安定した単一窓口モデルではλ < μが必要で、100%に近づくと待ち時間が急増します。同じ能力の窓口がc個ありμが一窓口当たりなら、利用率はλ/(cμ)です。',
     '待ち行列 利用率 到着率 サービス率',
     'リトルの法則 L = λW とM/M/1を学び、サービス時間・待ち時間・系内時間を区別しましょう。']],
  [4,'c',
    ['Подходит 123-456-7890: длины трёх групп — 3, 3 и 4 цифры.',
     'Разбейте шаблон ^\\d{2,4}-\\d+-\\d{3,4}$ на условия. Первая группа содержит от 2 до 4 цифр, вторая — хотя бы одну, третья — 3 или 4. Дефисы должны находиться между группами. Якоря ^ и $ привязывают совпадение к границам строки, а не позволяют найти только подходящий фрагмент. У 123-456-12 последняя группа слишком короткая; у 1-234-5678 первая содержит лишь одну цифру; у 12345-678-910 первая слишком длинная. В выбранной строке все ограничения выполняются одновременно. Не путайте + с *: звёздочка допускает пустую группу, плюс — нет. Здесь смысл цифр 0–9 задан самим условием.',
     'регулярные выражения квантификаторы якоря проверка строки',
     'Проверьте граничные случаи: 2 и 4 цифры, пустую среднюю группу, лишние символы. Сравните +, *, ? и точное число повторений.'],
    ['123-456-7890 matches: its three groups contain 3, 3 and 4 digits.',
     'Split ^\\d{2,4}-\\d+-\\d{3,4}$ into constraints. The first group needs 2–4 digits, the middle group at least one, and the last 3–4. Hyphens separate the groups. The ^ and $ anchors tie the match to the string boundaries rather than just a matching substring. In 123-456-12 the last group is too short; in 1-234-5678 the first has only one digit; in 12345-678-910 the first is too long. The selected string satisfies every constraint. Do not confuse + with *: only the latter allows zero repetitions. The question explicitly defines digits as 0–9.',
     'regular expressions quantifiers anchors full string validation',
     'Test boundary lengths, an empty middle group and extra characters. Compare +, *, ?, and exact repetition counts.'],
    ['123-456-7890 が一致します。三つの数字群の長さは3・3・4です。',
     '^\\d{2,4}-\\d+-\\d{3,4}$ を条件に分けます。最初は2～4桁、中央は1桁以上、最後は3～4桁で、群の間にはハイフンが必要です。^と$は境界を示し、文字列の一部分だけの一致では足りません。123-456-12は最後が2桁、1-234-5678は最初が1桁、12345-678-910は最初が5桁なので不適切です。選んだ文字列はすべての条件を同時に満たします。+は1回以上、*は0回も許す点に注意します。数字を0～9とすることは問題文で定義されています。',
     '正規表現 量指定子 アンカー 文字列 検証',
     '最小・最大の桁数、中央が空の場合、余分な文字を試し、+・*・?・固定回数を比較しましょう。']],
  [5,'c',
    ['Постфиксная запись: abc×+de×+. Оператор записывается после обоих своих аргументов.',
     'При левосторонней группировке получаем (a + (b×c)) + (d×e). Произведение b×c превращается в bc×; сумма с a — в abc×+; произведение d×e — в de×. Запишите две части и завершающий плюс: abc×+de×+. Проверка стеком: для a=2, b=3, c=4, d=5, e=6 сначала 3×4=12, затем 2+12=14, затем 5×6=30 и 14+30=44. Каждый оператор снимает два верхних значения и кладёт результат. Для вычитания и деления первое снятое значение является правым аргументом. В неверных ответах знак + оказывается перед недостающими аргументами либо меняет, что именно умножают.',
     'обратная польская постфиксная запись вычисление стек',
     'Переведите выражения с вычитанием и делением в обе стороны. Изучите алгоритм сортировочной станции для перевода из инфиксной записи.'],
    ['The postfix form is abc×+de×+: place each operator after both operands.',
     'With left grouping the expression is (a + (b×c)) + (d×e). Convert b×c to bc×, then the sum with a to abc×+. Convert d×e to de×. Join both pieces and append the final plus: abc×+de×+. Check with a stack using a=2, b=3, c=4, d=5, e=6: compute 3×4=12, 2+12=14, 5×6=30, then 14+30=44. Each operator pops two values and pushes the result. For subtraction or division, the first popped value is the right operand. Incorrect options either place an operator before enough operands or change which values are multiplied.',
     'postfix reverse Polish notation stack expression evaluation',
     'Convert expressions containing subtraction and division in both directions. Study the shunting-yard algorithm for infix-to-postfix conversion.'],
    ['後置記法は abc×+de×+ です。演算子を二つの引数の後に置きます。',
     '左からの結合で (a + (b×c)) + (d×e) と考えます。b×cはbc×、aとの和はabc×+、d×eはde×です。二つの式を並べ最後に+を付けるとabc×+de×+になります。a=2、b=3、c=4、d=5、e=6でスタック計算すると、3×4=12、2+12=14、5×6=30、14+30=44です。演算子ごとに頂上の二つを取り出して結果を積みます。減算や除算では先に取り出した値が右の引数です。誤った選択肢は引数がそろう前に演算子を置いたり、乗算対象を変えたりしています。',
     '後置記法 逆ポーランド記法 スタック 式の計算',
     '減算と除算を含む式を相互変換し、中置から後置へ変換する操車場アルゴリズムも学びましょう。']],
  [6,'d',
    ['Узел 11 станет правым потомком 10. Путь поиска: 14 → 7 → 12 → 10.',
     'В двоичном дереве поиска слева от узла находятся меньшие значения, справа — большие. Начните с корня: 11 < 14, идём влево к 7; 11 > 7 — вправо к 12; 11 < 12 — влево к 10; 11 > 10 — в свободную правую ссылку. Нельзя выбрать произвольный узел с подходящим непосредственным значением: важны ограничения всех предков. Справа от 3 в этом дереве должно быть значение меньше 7, поэтому 11 туда не подходит. Поддерево 16 находится справа от 14 и тоже исключается. Это обычная вставка без балансировки: существующие узлы не переставляются.',
     'двоичное дерево поиска BST вставка узла путь сравнения',
     'Изучите поиск, удаление и симметричный обход BST. Сравните вырожденное дерево со сбалансированными AVL и красно-чёрными деревьями.'],
    ['11 becomes the right child of 10. The search path is 14 → 7 → 12 → 10.',
     'In a binary search tree, smaller values belong on the left and larger ones on the right. Start at the root: 11 < 14, so go left to 7; 11 > 7, right to 12; 11 < 12, left to 10; 11 > 10, into its empty right link. You cannot choose any locally plausible parent: every ancestor’s constraint matters. A right child of 3 must still be below 7 in this tree, so 11 does not fit. The subtree rooted at 16 lies above 14 and is also excluded. This is ordinary insertion without rebalancing: existing nodes stay in place.',
     'binary search tree BST insertion ancestor constraints',
     'Study searching, deletion and inorder traversal. Compare a degenerate BST with balanced AVL and red-black trees.'],
    ['11は10の右の子になります。探索経路は14 → 7 → 12 → 10です。',
     '二分探索木では各節点より小さい値は左、大きい値は右に置きます。根から11 < 14なので7へ、11 > 7なので12へ、11 < 12なので10へ進み、11 > 10なので空いている右の子に挿入します。直近の親との大小だけでなく、祖先すべての条件を満たす必要があります。この木で3の右に置く値は7より小さくなければならず、11は置けません。16の部分木は14より大きい値の領域です。通常の挿入として扱い、平衡化による既存節点の移動は行いません。',
     '二分探索木 挿入 探索経路 祖先 大小関係',
     '探索・削除・通りがけ順を学び、偏った木とAVL木や赤黒木の違いを確認しましょう。']],
  [7,'b',
    ['F(231, 15) = 3. Это алгоритм Евклида для нахождения наибольшего общего делителя.',
     'На каждом шаге пару (x, y) заменяют на (y, x mod y). 231 = 15×15 + 6, поэтому F(231,15) = F(15,6). Далее 15 = 6×2 + 3, значит F(6,3). Затем 6 mod 3 = 0, получаем F(3,0). Условие остановки возвращает x, то есть 3, а не нулевой остаток. Почему это работает: общий делитель x и y делит также x−k×y, то есть остаток; и наоборот. Поэтому НОД сохраняется. Остаток меньше предыдущего положительного y, следовательно процесс завершится. Проверка: 231/3=77 и 15/3=5.',
     'алгоритм Евклида НОД рекурсия остаток от деления',
     'Напишите итеративную версию с циклом. Изучите НОК = |xy|/НОД для ненулевых чисел и расширенный алгоритм Евклида.'],
    ['F(231, 15) = 3. This is Euclid’s greatest-common-divisor algorithm.',
     'Replace (x, y) with (y, x mod y) at each step. Since 231 = 15×15 + 6, F(231,15) becomes F(15,6). Since 15 = 6×2 + 3, the next call is F(6,3). Then 6 mod 3 = 0 gives F(3,0). The base case returns x, namely 3, not the zero remainder. This works because a common divisor of x and y also divides x−k×y, the remainder, and conversely. Thus the gcd is preserved. Each remainder is smaller than the previous positive y, so the algorithm terminates. Check: 231/3=77 and 15/3=5.',
     'Euclidean algorithm gcd recursion modulo remainder',
     'Write an iterative loop version. Study lcm = |xy|/gcd for nonzero inputs and the extended Euclidean algorithm.'],
    ['F(231, 15) = 3です。最大公約数を求めるユークリッドの互除法です。',
     '各段階で(x, y)を(y, x mod y)に置き換えます。231 = 15×15 + 6なのでF(15,6)、15 = 6×2 + 3なのでF(6,3)、6 mod 3 = 0なのでF(3,0)になります。終了条件はxを返すため答えは3で、余りの0ではありません。xとyの公約数はx−k×yという余りも割り切り、その逆も成り立つので最大公約数は変わりません。余りは直前の正のyより小さくなり、処理は終了します。231/3=77、15/3=5でも確認できます。',
     'ユークリッドの互除法 最大公約数 再帰 剰余',
     'ループ版を書き、非零の数での最小公倍数 = |xy|/最大公約数と拡張互除法も学びましょう。']],
  [8,'c',
    ['Конструктор инициализирует объект: задаёт его начальное корректное состояние при создании.',
     'Класс описывает структуру и поведение, а объект содержит конкретные значения. Например, конструктор Account(owner) может сохранить владельца и установить balance = 0. Это часть создания готового к использованию объекта, а не обычное действие, которое выполняется только после полного завершения инициализации. Отрицать роль конструктора в инициализации поэтому неверно. Наследование конструкторов и порядок вызова базового конструктора зависят от языка: утверждение «во всех языках точно как обычные методы» слишком сильное. Не смешивайте выделение памяти, инициализацию полей и последующие вызовы методов — это разные понятия, даже если синтаксис скрывает часть шагов.',
     'ООП конструктор инициализация объекта класс экземпляр',
     'Изучите инварианты объекта, конструктор по умолчанию, параметры и вызов конструктора базового класса в выбранном языке.'],
    ['A constructor initializes an object, establishing its initial usable state during creation.',
     'A class describes structure and behaviour; an object holds specific values. For example, Account(owner) can store the owner and set balance = 0. Construction participates in making the object ready for use; it is not an ordinary operation performed only after initialization has fully finished. Denying the constructor’s initialization role is therefore incorrect. Constructor inheritance and base-constructor invocation rules depend on the language: “exactly like regular methods in all languages” is too strong. Distinguish memory allocation, field initialization and later method calls, even when a language’s syntax hides some of these steps.',
     'OOP constructor object initialization class instance invariants',
     'Study object invariants, default constructors, parameters and base-class constructor calls in your chosen language.'],
    ['コンストラクタはオブジェクトを初期化し、生成時に利用可能な初期状態を整えます。',
     'クラスは構造と振る舞いを定義し、インスタンスは具体的な値を持ちます。例えばAccount(owner)で所有者を保存しbalance = 0にできます。コンストラクタは初期化が完全に終わった後だけに行う通常操作ではなく、利用可能なオブジェクトを作る過程に関わります。初期化に役割がないという説明は誤りです。コンストラクタの継承や基底クラスの呼出し規則は言語によって異なるため、「すべての言語で通常メソッドと全く同じ」とは言えません。メモリ確保・フィールド初期化・後のメソッド呼出しを区別しましょう。',
     'オブジェクト指向 コンストラクタ 初期化 クラス インスタンス',
     '不変条件、デフォルトコンストラクタ、引数、基底クラスのコンストラクタ呼出しを使用言語で確認しましょう。']],
  [9,'c',
    ['Это регистр команд: он удерживает считанную команду перед её декодированием.',
     'На схеме поток идёт из основной памяти в a, затем в декодер команд. При выборке процессор получает машинную команду, сохраняет её в регистре команд (IR), после чего декодер определяет операцию и операнды. Счётчик команд (PC) содержит адрес команды для выборки, а не сам её код; это главное отличие. Аккумулятор хранит операнды или результаты вычислений. Кэш данных ускоряет доступ к данным памяти, но не является указанным регистром перед декодером. Современные процессоры сложнее этой учебной схемы, однако различие «адрес команды» и «содержимое команды» сохраняется.',
     'цикл процессора выборка декодирование регистр команд IR счётчик PC',
     'Проследите цикл fetch–decode–execute и роли PC, IR, регистров адреса и данных памяти. Затем изучите конвейер команд.'],
    ['It is the instruction register: it holds the fetched instruction before decoding.',
     'The diagram flows from main memory into a and then into the instruction decoder. During fetch, the processor obtains a machine instruction and holds it in the instruction register (IR); the decoder interprets its operation and operands. The program counter (PC) holds an instruction address for fetching, not the instruction bits themselves. An accumulator holds operands or calculation results. A data cache speeds access to memory data but is not the depicted register immediately before the decoder. Real processors are more complex than this teaching diagram, but the distinction between an instruction’s address and its contents remains essential.',
     'CPU fetch decode execute instruction register IR program counter PC',
     'Trace the fetch–decode–execute cycle and the roles of PC, IR, memory address and memory data registers. Then study pipelining.'],
    ['命令レジスタです。取り出した命令をデコード前に保持します。',
     '図は主記憶→a→命令デコーダという流れです。フェッチで読み出した機械命令を命令レジスタIRに保持し、デコーダが演算やオペランドを解釈します。プログラムカウンタPCが保持するのは取得する命令のアドレスであり、命令のビット列そのものではありません。アキュムレータは演算の値や結果を保持します。データキャッシュはメモリデータへのアクセスを速めるもので、図のデコーダ直前のレジスタではありません。実際のCPUは複雑でも、命令のアドレスと命令の内容は区別する必要があります。',
     '命令レジスタ IR プログラムカウンタ PC フェッチ デコード',
     '命令の取出し・解読・実行と各レジスタの役割を追い、次に命令パイプラインを学びましょう。']],
  [10,'d',
    ['При промахе кэша данные получают из основной памяти — в принятой здесь модели «кэш + память».',
     'Кэш хранит копии недавно или часто используемых блоков. Если нужный блок найден, это hit: данные читают из кэша. Если его нет, это miss: обращаются к следующему уровню памяти, а полученный блок обычно помещают в кэш для будущих обращений. Например, первое чтение массива может вызвать промах, а повторное чтение той же области — попадание. В этой задаче следующий уровень — основная память. В многоуровневом процессоре промах L1 может обслужить L2 или L3 без обращения к RAM. ROM не является обычным источником данных при попадании. Слова hit и miss описывают наличие нужного блока, а не успешность всей операции чтения.',
     'кэш процессора cache hit miss локальность иерархия памяти',
     'Изучите временную и пространственную локальность, строку кэша и среднее время доступа hit time + miss rate × miss penalty.'],
    ['On a cache miss, data comes from main memory in this question’s cache-plus-memory model.',
     'A cache keeps copies of recently or frequently used blocks. If the required block is present, a hit supplies it from cache. Otherwise a miss requires the next memory level; the fetched block is normally cached for later use. A first array access may miss while another access to the same area hits. Here the next level is main memory. In a multilevel processor, however, L2 or L3 may satisfy an L1 miss without reaching RAM. ROM is not the normal source on a cache hit. Hit and miss describe whether the block is present, not whether the complete read operation succeeds.',
     'CPU cache hit miss locality memory hierarchy',
     'Study temporal and spatial locality, cache lines, and average access time: hit time + miss rate × miss penalty.'],
    ['この問題の「キャッシュ＋主記憶」モデルでは、ミス時に主記憶からデータを取得します。',
     'キャッシュは最近または頻繁に使うブロックのコピーを保持します。必要なブロックがあればヒットで、キャッシュから読みます。なければミスで、次の記憶階層にアクセスし、通常は取得ブロックをキャッシュにも保存します。配列への初回アクセスはミスでも、同じ領域の再読出しはヒットすることがあります。本問の次の階層は主記憶ですが、多階層CPUではL1ミスをL2やL3で処理しRAMまで行かない場合もあります。ROMはヒット時の通常の取得先ではありません。ヒットとミスは必要ブロックの有無を表します。',
     'キャッシュ ヒット ミス 局所性 メモリ階層',
     '時間的・空間的局所性、キャッシュライン、平均アクセス時間の式を学びましょう。']],
  [11,'b',
    ['Максимум — 128 MB/s: 8 байт за цикл шины × 16 миллионов циклов шины в секунду.',
     'Сначала переведите ширину шины: 64 бита / 8 = 8 байт за передачу. Частота входного сигнала 64 MHz означает 64 миллиона тактов в секунду, но одна передача занимает 4 такта: 64/4 = 16 миллионов передач. Теперь 8×16 = 128 миллионов байт в секунду, то есть 128 MB/s. Здесь MB — десятичные мегабайты. Ответ 512 получается, если забыть четыре такта на цикл шины. Не умножайте результат ещё раз на разрядность процессора: ширина внешней шины уже учтена. Это теоретический предел без накладных расходов; реальная скорость может быть ниже. Всегда проверяйте единицы: бит/передача × передача/секунда ÷ 8 = байт/секунда.',
     'пропускная способность шины разрядность частота такты MB s',
     'Сравните MB/s с Mb/s и MiB/s. Решите обратную задачу: какая частота нужна при заданных ширине шины и числе тактов на передачу.'],
    ['The maximum is 128 MB/s: 8 bytes per bus cycle × 16 million bus cycles per second.',
     'Convert the bus width first: 64 bits / 8 = 8 bytes per transfer. A 64 MHz input supplies 64 million clock ticks per second, but a transfer takes four ticks, so there are 64/4 = 16 million transfers per second. Multiply: 8×16 = 128 million bytes per second, or 128 MB/s in decimal units. The value 512 ignores the four ticks per bus cycle. Do not multiply by processor bit width again: bus width is already included. This is a theoretical limit without overhead. Check dimensions: bits/transfer × transfers/second ÷ 8 = bytes/second.',
     'bus bandwidth width clock cycles bytes bits MB per second',
     'Compare MB/s, Mb/s and MiB/s. Solve for the clock frequency needed with a specified width and ticks per transfer.'],
    ['最大転送速度は128 MB/sです。1バスサイクル8バイト×毎秒1600万サイクルで求めます。',
     'まずバス幅64ビットを8で割ると1回8バイトです。入力64 MHzは毎秒6400万クロックですが、転送1回に4クロック必要なので6400万/4 = 1600万回です。8×1600万 = 毎秒1億2800万バイト、10進の単位で128 MB/sとなります。512は4クロックという条件を忘れた値です。外部バス幅を既に使っているため、CPUのビット数をもう一度掛けません。これは付加処理を無視した理論値で、実効速度は低くなり得ます。ビット/回×回/秒÷8 = バイト/秒と単位も確認します。',
     'バス 転送速度 バス幅 クロック バイト ビット',
     'MB/s・Mb/s・MiB/sの違いと、必要な周波数を逆算する問題を練習しましょう。']],
  [12,'b',
    ['Для двух дисков подходит RAID 1: зеркалирование сохраняет данные при отказе одного диска.',
     'RAID 1 записывает одинаковые данные на оба диска. Два диска по 2 TB дают около 2 TB полезной ёмкости: вторая копия обеспечивает резервирование. RAID 0 распределяет блоки без резервирования и не выдерживает отказ диска. Для RAID 5 нужно минимум 3 диска, для RAID 6 — 4, поэтому они не подходят. Зеркало не заменяет резервную копию: удаление файла или его повреждение может отразиться на обеих копиях.',
     'RAID 0 1 5 6 зеркалирование отказоустойчивость резервная копия',
     'Сравните полезную ёмкость, число дисков и допустимые отказы. Изучите восстановление массива и отдельные резервные копии с историей версий.'],
    ['RAID 1 fits two drives: mirroring preserves data when one drive fails.',
     'RAID 1 writes the same data to both drives. Two 2 TB drives provide about 2 TB of usable capacity; the second copy supplies redundancy. RAID 0 stripes blocks without redundancy and cannot tolerate a drive failure. RAID 5 needs at least 3 drives and RAID 6 at least 4. Mirroring is not a backup: deletion or corruption can affect both copies.',
     'RAID 0 1 5 6 mirroring fault tolerance backup',
     'Compare usable capacity, drive counts and tolerated failures. Study rebuilding and separate versioned backups.'],
    ['2台ならRAID 1です。ミラーリングで1台の故障に対応します。',
     '両方のディスクに同じ内容を記録します。2 TBを2台使っても有効容量は約2 TBで、残りは冗長化に使います。RAID 0は分散記録のみで故障への冗長性がありません。RAID 5は最低3台、RAID 6は最低4台必要です。ミラーはバックアップの代わりではなく、削除やデータ破損が両方に反映される場合があります。',
     'RAID 0 1 5 6 ミラーリング 耐障害性 バックアップ',
     '必要台数・有効容量・許容故障数を比較し、再構築と世代管理付きバックアップも学びましょう。']],
  [13,'b',
    ['Порядок: (iii) → (iv) → (ii) → (i). Текущее состояние → новая нагрузка → конфигурация → проверка.',
     'Сначала используйте уже накопленный мониторинг: каковы загрузка CPU, память, дисковые задержки и текущая пропускная способность? Затем уточните у пользователей объём новой работы и требуемое время обработки. На этой основе предложите конфигурацию: дополнительные серверы, распределение задач или устранение узкого места. Наконец оцените, удовлетворяет ли предложение требованиям, и при необходимости пересмотрите его. Например, удвоение серверов не поможет автоматически, если ограничение — общая база данных. В неверных последовательностях конфигурацию выбирают до сбора новых требований либо оценивают ещё не предложенный вариант. Это логика данной задачи; на практике сбор требований и измерения могут повторяться итеративно.',
     'планирование мощностей capacity planning мониторинг нагрузка узкое место',
     'Изучите нагрузочное тестирование, пиковую и среднюю нагрузку, запас мощности. Сравните вертикальное и горизонтальное масштабирование.'],
    ['The order is (iii) → (iv) → (ii) → (i): baseline, new demand, configuration, evaluation.',
     'Use the existing monitoring first: current CPU use, memory, disk delays and throughput. Then ask users about the new workload and required processing times. Use both inputs to propose a configuration: more servers, distributed work or removal of a bottleneck. Finally evaluate the proposal against requirements and revise if necessary. Doubling application servers, for example, will not automatically solve a shared database bottleneck. Incorrect sequences propose a configuration before collecting new requirements or evaluate one before proposing it. This is the question’s sequence; in practice measurement and requirements gathering can be iterative.',
     'capacity planning workload baseline bottleneck performance requirements',
     'Study load testing, peak versus average demand and capacity headroom. Compare vertical and horizontal scaling.'],
    ['順序は(iii) → (iv) → (ii) → (i)です。現状把握、新負荷の要件、構成案、評価の順です。',
     'まず既存の監視情報でCPU・メモリ・ディスク遅延・処理量を把握します。次に利用者から新しい業務量と必要な処理時間を聞きます。両方を基にサーバ追加や分散処理などの構成案を考え、最後に要件を満たすか評価して必要なら見直します。例えば共通データベースが制約なら、アプリサーバを倍にするだけでは解決しません。誤った順序は新要件を知る前に構成を決めたり、案がない段階で評価したりしています。本問ではこの順ですが、実務では測定や要件確認を反復することもあります。',
     'キャパシティプランニング 現状分析 負荷 ボトルネック',
     '負荷試験、ピークと平均の違い、余裕率、スケールアップとスケールアウトを学びましょう。']],
  [14,'d',
    ['Загрузка около 97%: 1 − 0.3³ = 0.973, то есть 97.3% до округления.',
     'CPU простаивает, только когда все три задания одновременно ждут ввод-вывод. В учебной модели с независимыми ожиданиями вероятность этого равна 0.3×0.3×0.3 = 0.027. Значит процессор занят в оставшейся доле времени: 1−0.027 = 0.973. Умножаем на 100 и округляем до предлагаемого целого процента: 97. Нельзя складывать 30% трёх заданий: периоды их ожидания перекрываются, а CPU переключается на готовое задание. Формула для n заданий — U = 1−pⁿ. Она предполагает независимость ожиданий и игнорирует накладные расходы переключения; в реальной системе коррелированные ожидания могут дать другой результат.',
     'мультипрограммирование загрузка процессора 1 минус p в степени n',
     'Посчитайте загрузку для 1, 2 и 3 заданий. Изучите независимость событий, вероятность дополнения и влияние переключения контекста.'],
    ['Utilization is about 97%: 1 − 0.3³ = 0.973, or 97.3% before rounding.',
     'The CPU is idle only when all three jobs are simultaneously waiting for I/O. Assuming independent waits, that probability is 0.3×0.3×0.3 = 0.027. The busy fraction is its complement: 1−0.027 = 0.973. Multiply by 100 and round to the offered whole percentage, 97. Do not add the jobs’ 30% waiting fractions: their waits overlap and the CPU can run another ready job. For n jobs the model is U = 1−pⁿ. It assumes independent waiting and neglects context-switch overhead. Correlated waits in a real system may produce a different result.',
     'multiprogramming CPU utilization 1 minus p power n',
     'Calculate utilization for 1, 2 and 3 jobs. Study independent events, complementary probability and context-switch costs.'],
    ['CPU利用率は約97%です。1 − 0.3³ = 0.973なので、丸める前は97.3%です。',
     'CPUが空くのは三つのジョブが同時にI/O待ちになるときです。待ちが独立という学習モデルでは0.3×0.3×0.3 = 0.027で、稼働する確率は余事象の1−0.027 = 0.973です。100倍し選択肢の整数百分率に丸めると97です。三つの30%を単純に足してはいけません。待ち時間は重なり、CPUは実行可能な別のジョブへ切り替えられます。一般式はU = 1−pⁿです。待ちの独立性と切替コスト無視が前提で、実際に待ちが相関すると結果は異なり得ます。',
     '多重プログラミング CPU利用率 1-p^n 独立',
     'ジョブ数1・2・3で比較し、独立な事象、余事象、コンテキストスイッチを学びましょう。']],
  [15,'c',
    ['Среднее суммарное ожидание — 11.5 ms. Для P1–P4 оно равно 0, 17, 10 и 19 ms.',
     'Квант 5 ms ограничивает один ход, но завершившийся процесс освобождает CPU раньше. Расписание: P1 0–5; P2 5–10; P3 10–14; P4 14–19; P2 19–24; P4 24–27; P2 27–30. Остаток незавершённого процесса возвращается в конец очереди. Времена завершения P1–P4 равны 5, 30, 14, 27. Поскольку все прибыли в момент 0, ожидание = завершение − длительность CPU: 5−5=0, 30−13=17, 14−4=10, 27−8=19. Среднее (0+17+10+19)/4 = 11.5. Ожидание включает промежутки между всеми квантами, а не только время до первого запуска. Накладные расходы переключения в условии не заданы и считаются нулевыми.',
     'Round Robin квант времени среднее ожидание диаграмма Ганта',
     'Различайте waiting time, response time и turnaround time. Пересчитайте пример с другим квантом и сравните с FCFS.'],
    ['Mean total waiting time is 11.5 ms. P1–P4 wait 0, 17, 10 and 19 ms respectively.',
     'The 5 ms quantum limits a turn, but a process that finishes releases the CPU early. Schedule: P1 0–5; P2 5–10; P3 10–14; P4 14–19; P2 19–24; P4 24–27; P2 27–30. Unfinished processes return to the queue’s tail. Completion times for P1–P4 are 5, 30, 14, 27. All arrived at 0, so waiting = completion − CPU duration: 5−5=0, 30−13=17, 14−4=10, 27−8=19. Average: (0+17+10+19)/4 = 11.5. Waiting includes gaps between all turns, not only the delay before first execution. The question specifies no context-switch cost, so it is taken as zero.',
     'Round Robin scheduling time quantum average waiting time Gantt chart',
     'Distinguish waiting time, response time and turnaround time. Recalculate with another quantum and compare with FCFS.'],
    ['平均の合計待ち時間は11.5 msです。P1～P4は順に0・17・10・19 ms待ちます。',
     '量子5 msは1回の上限で、処理が終われば早くCPUを渡します。順序はP1 0–5、P2 5–10、P3 10–14、P4 14–19、P2 19–24、P4 24–27、P2 27–30です。未完了のプロセスは待ち行列の末尾へ戻します。P1～P4の終了時刻は5・30・14・27です。全員時刻0に到着したので、待ち時間は終了時刻−CPU実行時間となり、5−5=0、30−13=17、14−4=10、27−8=19です。平均は(0+17+10+19)/4 = 11.5です。初回実行までだけでなく、各量子の間の待ちも含みます。切替コストは指定がないので0とします。',
     'ラウンドロビン タイムクォンタム 平均待ち時間 ガントチャート',
     '待ち時間・初回応答時間・ターンアラウンド時間を区別し、量子を変えてFCFSとも比較しましょう。']],
  [16,'d',
    ['Это компоновщик (linker): он объединяет объектные модули и разрешает ссылки между ними.',
     'Например, main.c вызывает функцию sum, определённую в sum.c. После отдельной компиляции получаются main.o и sum.o. Компоновщик связывает вызов из одного модуля с определением в другом, подключает нужные библиотеки и формирует исполняемый файл. Компилятор переводит исходную программу, ассемблер — ассемблерные команды в объектный код; интерпретатор выполняет программу через свою среду. Драйвер gcc может запустить все этапы одной командой, но это не делает их одной операцией. Если определение sum не предоставлено, ошибка undefined reference появляется на этапе компоновки, даже если отдельные исходные файлы успешно скомпилированы.',
     'компилятор ассемблер компоновщик linker объектные файлы undefined reference',
     'Соберите программу из двух C-файлов по этапам. Сравните статическое и динамическое связывание и изучите таблицу символов.'],
    ['The linker combines object modules and resolves references between them.',
     'Suppose main.c calls sum, defined in sum.c. Separate compilation produces main.o and sum.o. The linker connects the call with its definition, includes required libraries and produces an executable. A compiler translates source code; an assembler translates assembly into object code; an interpreter executes through its runtime. The gcc driver may invoke several stages with one command, but their jobs remain distinct. Omitting the definition of sum can cause an undefined-reference error during linking even when each source file compiled successfully.',
     'compiler assembler linker object files undefined reference',
     'Build a two-file C program stage by stage. Compare static and dynamic linking and inspect a symbol table.'],
    ['リンカです。オブジェクトモジュールを結合し、相互の参照を解決します。',
     'main.cがsum.cの関数sumを呼ぶ場合、個別のコンパイルでmain.oとsum.oができます。リンカが呼出しと定義を結び、必要なライブラリも使って実行ファイルを作ります。コンパイラはソースの翻訳、アセンブラはアセンブリからオブジェクトコードへの変換、インタプリタは実行環境を介した実行を担当します。gccの一つのコマンドが複数段階を起動しても役割は別です。sumの定義がなければ、個別コンパイルが成功してもリンク時に未定義参照のエラーになり得ます。',
     'コンパイラ アセンブラ リンカ オブジェクトファイル 未定義参照',
     'Cの2ファイルを段階別にビルドし、静的・動的リンクとシンボル表を学びましょう。']],
  [17,'b',
    ['Нужен NAND: X = NOT(A AND B). Только для A=1 и B=1 выход равен 0.',
     'Начните с таблицы истинности AND: для входов 00, 01, 10, 11 выходы равны 0, 0, 0, 1. Инверсия каждого выхода даёт NAND: 1, 1, 1, 0 — ровно условие задачи. OR даёт 0 только при двух нулях. XOR даёт 0 при равных входах, то есть и для 00, и для 11, поэтому не подходит слову «только». Проверяйте все четыре строки, а не одну комбинацию 11. Название NAND означает NOT AND, а не NOT A AND B: скобки вокруг всей конъюнкции важны.',
     'логический элемент NAND И НЕ таблица истинности AND OR XOR',
     'Постройте таблицы NOR и XNOR. Проверьте законы де Моргана и попробуйте собрать NOT, AND и OR только из NAND.'],
    ['Use NAND: X = NOT(A AND B). Its output is 0 only for A=1 and B=1.',
     'Start with AND: for inputs 00, 01, 10, 11 its outputs are 0, 0, 0, 1. Invert each output to obtain NAND: 1, 1, 1, 0, exactly as required. OR is 0 only when both inputs are 0. XOR is 0 whenever the inputs are equal, including both 00 and 11, so it fails the word “only”. Check all four rows, not just the 11 combination. NAND means NOT AND, not NOT A AND B: the negation applies to the entire conjunction.',
     'NAND logic gate truth table AND OR XOR',
     'Build NOR and XNOR truth tables. Verify De Morgan’s laws and construct NOT, AND and OR using only NAND gates.'],
    ['NANDです。X = NOT(A AND B)なので、両入力が1の場合だけ出力0です。',
     'ANDの真理値表は入力00・01・10・11に対して出力0・0・0・1です。全出力を反転するとNANDの1・1・1・0になり、条件を満たします。ORは両方0の場合だけ0です。XORは入力が等しい00と11の両方で0なので「両方1のときだけ」という条件に合いません。11の一行だけでなく四行すべてを確認しましょう。NANDは論理積全体の否定で、NOT A AND Bではありません。括弧の位置が重要です。',
     'NAND 論理積 否定 真理値表 AND OR XOR',
     'NORとXNORの表、ド・モルガンの法則、NANDだけでNOT・AND・ORを作る方法を学びましょう。']],
  [18,'a',
    ['Получится 73940. Контрольная цифра — последняя цифра числа 11−(56 mod 11)=10, то есть 0.',
     'Сопоставьте цифры данных 7394 и веса 1234 по позициям: 7×1 + 3×2 + 9×3 + 4×4 = 7+6+27+16 = 56. Делим на основание 11: 56 = 5×11 + 1, остаток 1. По заданному правилу вычитаем его из 11: 11−1 = 10. В качестве контрольной берут только последнюю десятичную цифру 10, то есть 0, и дописывают к 7394. Не дописывайте остаток 1 или всё число 10. В общем виде именно для этой задачи: check = (11−(sum mod 11)) mod 10. Не заменяйте алгоритм знакомым стандартом mod 11: правила обработки 10 и 11 в других системах могут отличаться. Контрольная цифра помогает обнаруживать ошибки, но не является криптографической защитой.',
     'контрольная цифра взвешенная сумма mod 11 остаток',
     'Проверьте изменение одной цифры и перестановку двух соседних. Сравните заданный алгоритм с Luhn, ISBN и CRC.'],
    ['The result is 73940. The check digit is the last digit of 11−(56 mod 11)=10, namely 0.',
     'Align data 7394 with weights 1234: 7×1 + 3×2 + 9×3 + 4×4 = 7+6+27+16 = 56. Since 56 = 5×11 + 1, the remainder is 1. Subtract it from 11 to obtain 10. The rule takes only the last decimal digit, 0, and appends it to 7394. Do not append the remainder 1 or the whole value 10. For this question the formula is check = (11−(sum mod 11)) mod 10. Do not substitute a familiar mod-11 standard: other systems may handle 10 and 11 differently. Check digits detect some input errors; they are not cryptographic protection.',
     'weighted checksum check digit modulo 11 remainder',
     'Test a one-digit change and an adjacent transposition. Compare this rule with Luhn, ISBN and CRC.'],
    ['結果は73940です。11−(56 mod 11)=10の最後の桁0を付けます。',
     '7394と重み1234を同じ位置で掛けると7×1 + 3×2 + 9×3 + 4×4 = 7+6+27+16 = 56です。56 = 5×11 + 1なので余り1を11から引き10になります。指定ではその十進数の最後の桁だけを使うためチェック桁は0で、7394に追加します。余り1や10全体を付けてはいけません。この問題の式はcheck = (11−(sum mod 11)) mod 10です。他のmod 11方式は10や11の扱いが異なる場合があるため、既知の規格に置き換えず指定手順に従います。チェック桁は入力誤りの検出用で暗号学的保護ではありません。',
     'チェックディジット 加重和 モジュラス11 剰余',
     '一桁の誤りや隣接桁の入替えを試し、Luhn・ISBN・CRCとの違いを学びましょう。']],
  [19,'b',
    ['Отношению соответствует таблица. Кортежу соответствует строка, атрибуту — столбец.',
     'Реляционная модель описывает данные математически, реализация SQL — практически. Для отношения Employee атрибуты id и name становятся столбцами, а конкретный сотрудник — строкой. Домен задаёт множество допустимых значений и не ограничен строковым типом: возможны числа, даты и ограничения. В математическом отношении порядок кортежей и атрибутов не задаёт смысл данных. SQL-таблица или результат запроса могут содержать одинаковые строки, если уникальность не обеспечена; поэтому «ни кортежи, ни строки не имеют дубликатов» неверно для реализации. DISTINCT удаляет дубликаты результата, а PRIMARY KEY или UNIQUE ограничивают допустимые записи.',
     'реляционная модель отношение кортеж атрибут домен таблица SQL',
     'Изучите ключи, ограничения уникальности и NULL. Сравните математическое множество с SQL-мультимножеством и ORDER BY с порядком хранения.'],
    ['A relation maps to a table; a tuple maps to a row and an attribute to a column.',
     'The relational model is mathematical; SQL is an implementation. In Employee, attributes id and name become columns and an employee becomes a row. A domain is a set of allowed values, not merely a character type: numbers, dates and constraints are possible. Tuple and attribute order do not define the meaning of a mathematical relation. SQL tables or query results can contain duplicate rows unless uniqueness is enforced. Thus the claim that neither tuples nor rows have duplicates is unsuitable for the implementation. DISTINCT removes duplicate result rows; PRIMARY KEY or UNIQUE constrains stored records.',
     'relational model relation tuple attribute domain SQL table',
     'Study keys, uniqueness and NULL. Compare mathematical sets with SQL bags, and ORDER BY with physical storage order.'],
    ['関係は表、タプルは行、属性は列に対応します。',
     '関係モデルは数学的な表現、SQLは実装です。Employeeのid・nameという属性は列になり、具体的な従業員は行になります。定義域は許される値の集合で、文字列だけでなく数値・日付・制約なども扱います。数学的な関係ではタプルや属性の順序はデータの意味を決めません。一方、SQLの表や結果は一意性を強制しなければ重複行を持てるため、「タプルも行も重複しない」は実装について不適切です。DISTINCTは結果の重複を除き、PRIMARY KEYやUNIQUEは格納する値を制約します。',
     '関係モデル 関係 タプル 属性 定義域 SQL 表',
     'キー・一意性・NULL、集合とSQLの重複を許す扱い、ORDER BYと物理格納順の違いを学びましょう。']],
  [20,'d',
    ['В учебной формулировке 3NF: уже выполнена 2NF и устранена транзитивная зависимость неключевых атрибутов от ключа.',
     'Пример: Employee(employeeId, departmentId, departmentName). Если employeeId определяет departmentId, а departmentId определяет departmentName, то название отдела зависит от сотрудника через отдел. При переименовании отдела придётся менять множество строк, иначе появятся противоречия. Разделите данные на Employee(employeeId, departmentId) и Department(departmentId, departmentName). Отсутствие повторяющихся групп относится к 1NF; устранение частичной зависимости от составного ключа — к 2NF. Повторить только условие 2NF недостаточно для 3NF. Кандидатные ключи не исчезают. Строгий критерий 3NF: для каждой нетривиальной зависимости X→A либо X является суперключом, либо A входит в некоторый кандидатный ключ.',
     'нормализация базы данных 1NF 2NF 3NF транзитивная зависимость',
     'Найдите зависимости в собственной таблице заказов и выполните декомпозицию без потерь. Затем сравните 3NF и BCNF.'],
    ['In the introductory formulation, 3NF adds removal of transitive non-key dependencies on the key to 2NF.',
     'Consider Employee(employeeId, departmentId, departmentName). If employeeId determines departmentId and departmentId determines departmentName, the name depends on the employee indirectly. Renaming a department requires many row updates and risks inconsistencies. Split it into Employee(employeeId, departmentId) and Department(departmentId, departmentName). Removing repeating groups belongs to 1NF; removing partial dependency on a composite key belongs to 2NF. Restating 2NF alone does not ensure 3NF, and candidate keys do not disappear. The formal 3NF criterion for each nontrivial X→A is: X is a superkey or A belongs to some candidate key.',
     'database normalization 1NF 2NF 3NF transitive dependency',
     'Identify dependencies in an order table and perform a lossless decomposition. Then compare 3NF with BCNF.'],
    ['入門的には、2NFを満たし非キー属性のキーへの推移的従属を除いた状態が3NFです。',
     'Employee(employeeId, departmentId, departmentName)で、employeeIdからdepartmentId、departmentIdからdepartmentNameが決まると、部署名は社員に間接的に従属します。部署名変更で多数の行を直す必要があり、不整合の原因になります。Employee(employeeId, departmentId)とDepartment(departmentId, departmentName)に分けます。繰返し項目の除去は1NF、複合キーへの部分従属の除去は2NFです。2NFの条件だけでは3NFを保証せず、候補キーがなくなるわけでもありません。厳密には各非自明なX→Aについて、Xがスーパーキーか、Aがいずれかの候補キーの構成属性であることが条件です。',
     'データベース 正規化 第三正規形 推移的関数従属',
     '注文表の関数従属を見つけ、情報を失わない分解を練習して3NFとBCNFを比較しましょう。']],
  [21,'d',
    ['Кандидатные ключи: PTY, QTY и STY. Каждый определяет все атрибуты и не содержит лишних.',
     'Замыкание X⁺ — все атрибуты, которые можно вывести из X по зависимостям. T и Y отсутствуют справа во всех правилах, поэтому вывести их нельзя: они обязательны в каждом ключе. Из TY получаем R по T→R, но не P, Q и S. Добавим P: P→Q, затем QR→S, поэтому PTY⁺ содержит все шесть атрибутов. Добавим вместо P атрибут Q: T→R, QR→S, S→P — QTY тоже ключ. Для STY: S→P→Q и T→R. Удаление T или Y всегда разрушает полноту, а без третьего атрибута остаётся неполное TY. Других минимальных ключей нет: из TYR нельзя получить P/Q/S, а добавление двух из P/Q/S уже избыточно. QRY не ключ, потому что не определяет T.',
     'кандидатный ключ замыкание атрибутов функциональные зависимости',
     'Находите все минимальные ключи через замыкания. Отличайте кандидатный ключ от суперключа и затем проверяйте 2NF, 3NF и BCNF.'],
    ['The candidate keys are PTY, QTY and STY. Each determines every attribute without redundant members.',
     'X⁺ denotes the attributes derivable from X. T and Y never appear on a dependency’s right side, so both must be present in every key. TY determines R through T→R, but not P, Q or S. Adding P gives Q through P→Q, then S through QR→S: PTY is a key. Adding Q instead gives R, then S, then P, so QTY works. STY obtains P and Q from S, and R from T. Removing T or Y loses completeness; removing the third attribute leaves insufficient TY. TYR cannot reach P/Q/S, while adding two of P/Q/S is redundant. QRY is not a key because it cannot determine T.',
     'candidate keys attribute closure functional dependencies minimal superkey',
     'Find all minimal keys using closures. Distinguish candidate keys from superkeys before checking 2NF, 3NF and BCNF.'],
    ['候補キーはPTY・QTY・STYです。全属性を決定でき、余分な属性を含みません。',
     'X⁺はXから関数従属を使って導ける属性全体です。TとYはどの規則の右辺にもないため導出できず、全キーに必要です。TYからT→RでRを得ますがP・Q・Sは得られません。Pを加えるとP→Q、QR→Sで全属性に達します。Qを加えてもT→R、QR→S、S→Pで全属性になります。STYではS→P→QとT→Rを使います。TかYを除くと不足し、三つ目を除くとTYだけなので、三つとも最小です。TYRからはP・Q・Sを得られず、P・Q・Sの二つを加えるのは冗長です。QRYはTを決定できません。',
     '候補キー 属性閉包 関数従属 スーパーキー 最小性',
     '閉包で全候補キーを求め、スーパーキーとの違いと2NF・3NF・BCNFの判定を練習しましょう。']],
  [22,'d',
    ["Нужное условие — name LIKE 'A%': сначала A, затем любое число символов, включая ноль.",
     "В SQL LIKE символ % обозначает любое число символов, включая ноль, а _ — ровно один. Поэтому A% подходит для A, Al и Anna. A_ подходит только для двухсимвольного имени, например Al, но не Anna. %A ищет окончание, а %A_ — A перед последним символом. WHERE отбирает строки, а SELECT * возвращает все столбцы выбранных студентов. В реальном SQL используйте обычные одинарные кавычки, не типографские из PDF. Чувствительность к регистру зависит от СУБД и правил сравнения; не считайте автоматически, что a и A одинаковы.",
     'SQL LIKE процент подчёркивание начинается с буквы',
     'Сравните начало, конец и вхождение подстроки. Изучите экранирование буквальных % и _, NULL и правила сравнения строк.'],
    ["Use name LIKE 'A%': A first, followed by zero or more characters.",
     "In SQL LIKE, % matches any number of characters, including zero; _ matches exactly one. A% therefore matches A, Al and Anna. A_ matches only a two-character name such as Al, not Anna. %A tests the ending, while %A_ places A immediately before the last character. WHERE filters rows and SELECT * returns every column for those students. Executable SQL uses straight single quotes, not the typographic quotes in the PDF. Case sensitivity depends on the database and collation: do not assume lowercase a equals uppercase A.",
     'SQL LIKE percent underscore starts with prefix matching',
     'Compare prefixes, suffixes and substrings. Study escaping literal % and _, NULL and collations.'],
    ["name LIKE 'A%' を使います。先頭がAで、後ろは0文字以上です。",
     'SQLのLIKEでは%が0文字以上の任意文字列、_がちょうど1文字を表します。A%はA・Al・Annaに一致します。A_はAlのような2文字だけで、Annaには一致しません。%Aは末尾がA、%A_は最後から2文字目がAという条件です。WHEREが行を絞り、SELECT *が選ばれた学生の全列を返します。実行するSQLにはPDFの装飾的な引用符でなく通常の単一引用符を使います。大小文字の区別はDBMSと照合規則によるため、aとAが必ず同じとは考えません。',
     'SQL LIKE パーセント アンダースコア 前方一致',
     '前方・後方・部分一致、%と_自体のエスケープ、NULL、照合順序を学びましょう。']],
  [23,'d',
    ['Журнал хранит сведения об изменениях для восстановления: в учебной модели — значения до и после обновления.',
     'Представьте перевод денег между счетами. Если сбой произошёл посередине, база должна сохранить атомарность: завершить подтверждённые изменения или отменить незавершённые. Записи журнала позволяют выполнить REDO и, в соответствующей схеме журналирования, UNDO. Это не то же самое, что полная резервная копия или зеркало диска. Запись изменённых страниц из памяти в устойчивое хранилище связана с контрольными точками и сокращением восстановления, но не определяет журнал. Конкретные СУБД используют разные форматы записей: не всякий журнал буквально хранит две полные копии строки. Важно назначение — восстановить согласованное состояние по истории операций.',
     'журнал транзакций база данных WAL REDO UNDO checkpoint',
     'Изучите ACID, commit, контрольные точки и восстановление из резервной копии с последующим применением журнала.'],
    ['A log records changes for recovery: in this introductory model, values before and after an update.',
     'Imagine a transfer between accounts interrupted halfway through. The database must retain atomicity by preserving committed changes and undoing incomplete work. Log records support REDO and, in suitable logging schemes, UNDO. A log is neither a full backup nor a disk mirror. Flushing changed memory pages to durable storage relates to checkpointing and shorter recovery, but does not define a log. Real DBMS products use different record formats; not every log literally stores two complete row copies. The essential role is recovering a consistent state from recorded changes.',
     'database transaction log WAL REDO UNDO checkpoint recovery',
     'Study ACID, commit, checkpoints and restoring a backup followed by replaying its log.'],
    ['ログは復旧用に変更内容を記録します。本問の基本モデルでは更新前後の値です。',
     '口座間の振替の途中で障害が起きても、確定済み変更を保持し未完了処理を取り消して原子性を守る必要があります。ログはREDOや、対応する方式でのUNDOを支えます。全体のバックアップやディスクのミラーとは別です。メモリ中の変更ページを永続化することはチェックポイントや復旧時間短縮に関わりますが、ログそのものの定義ではありません。DBMSごとに記録形式が異なり、必ず行の完全な前後コピーを持つわけではありません。変更の記録から整合した状態を復元する役割が重要です。',
     'トランザクションログ WAL REDO UNDO チェックポイント',
     'ACID・コミット・チェックポイントと、バックアップ復元後のログ適用を学びましょう。']],
  [24,'b',
    ['NAT преобразует IP-адреса, например частный внутренний адрес в публичный внешний.',
     'Компьютер 192.168.1.10 отправляет пакет наружу. Пограничный маршрутизатор может заменить адрес источника своим публичным адресом и выполнить обратное преобразование для ответа. Если несколько устройств используют один публичный адрес, обычно различают соединения также по портам: это NAPT/PAT. Таблица соответствий позволяет вернуть ответ нужному устройству. NAT не является веб-кэшем, системой обнаружения вторжений или правилом фильтрации: эти функции могут находиться на том же маршрутизаторе, но решают другие задачи. Преобразование адресов само по себе не шифрует трафик и не заменяет политику межсетевого экрана.',
     'NAT PAT NAPT частный публичный IP адрес таблица трансляций',
     'Сравните статический NAT, динамический NAT и PAT. Проследите адреса и порты в запросе и ответе, затем изучите IPv6.'],
    ['NAT translates IP addresses, such as an internal private address into an external public one.',
     'A host at 192.168.1.10 sends a packet outward. The boundary router can replace its source address with a public address and reverse the mapping for replies. Sharing one public address across devices usually also translates ports: NAPT/PAT. A mapping table identifies the internal recipient. NAT is not web caching, intrusion detection or packet filtering, even when one router provides all these features. Address translation does not encrypt traffic or replace firewall policy.',
     'NAT PAT NAPT private public IP address translation table',
     'Compare static NAT, dynamic NAT and PAT. Trace request and response addresses and ports, then study IPv6.'],
    ['NATはIPアドレスを変換します。例えば内部のプライベートアドレスを外部の公開アドレスへ変換します。',
     '192.168.1.10から外部へ送るパケットの送信元を、境界ルータが公開アドレスに置き換え、応答時に逆変換します。複数端末で一つの公開アドレスを共有する場合、通常はポート番号も使うNAPT/PATで区別します。対応表で応答先の端末を特定します。Webキャッシュ・侵入検知・パケットフィルタリングとは別機能です。同じルータに搭載されていても目的は異なります。アドレス変換自体は暗号化ではなく、ファイアウォールの方針も代替しません。',
     'NAT NAPT PAT プライベート グローバル IPアドレス変換',
     '静的NAT・動的NAT・PATを比較し、要求と応答のアドレス・ポートを追ってIPv6も学びましょう。']],
  [25,'c',
    ['Это управление потоком (flow control): отправитель учитывает, сколько данных способен принять получатель.',
     'Если передатчик выдаёт кадры быстрее, чем получатель освобождает буфер, данные могут потеряться. Управление потоком ограничивает объём неподтверждённых или разрешённых к отправке данных. Например, в stop-and-wait отправляют один кадр и ждут подтверждения; скользящее окно допускает несколько. Congestion control защищает сеть от перегрузки, а не только буфер конечного получателя. Error control отвечает за обнаружение ошибок и восстановление, MAC — за доступ к общей среде. Механизмы могут взаимодействовать: подтверждения применяют для нескольких целей. Термин flow control встречается и на транспортном уровне, но здесь спрашивают его функцию на канальном.',
     'управление потоком flow control stop and wait sliding window',
     'Сравните окно получателя и ограничение из-за перегрузки. Посчитайте, как задержка подтверждения влияет на загрузку канала.'],
    ['It is flow control: the sender respects the receiver’s ability to accept data.',
     'If frames arrive faster than the receiver empties its buffer, data can be lost. Flow control limits outstanding or permitted transmissions. Stop-and-wait sends one frame and awaits acknowledgment; a sliding window permits several. Congestion control protects the network from overload, not merely the destination buffer. Error control handles corruption and recovery, while MAC arbitrates access to shared media. These mechanisms can interact: acknowledgments may serve several purposes. Flow control also exists at the transport layer, but this question asks about its data-link role.',
     'flow control stop and wait sliding window congestion control',
     'Compare receiver-window and congestion limits. Calculate how acknowledgment delay affects link utilization.'],
    ['フロー制御です。送信側のデータ量を受信側の受入能力に合わせます。',
     '受信側がバッファを空ける速度より速くフレームが届くと、あふれる可能性があります。フロー制御は送信可能量や未確認データ量を制限します。Stop-and-waitは1フレームごとに確認を待ち、スライディングウィンドウは複数を許します。輻輳制御は受信端末だけでなくネットワーク全体の過負荷を扱います。誤り制御は破損検出と回復、MACは共有媒体へのアクセスを扱います。確認応答は複数の目的に使われることもあります。トランスポート層にもフロー制御がありますが、本問はデータリンク層の役割です。',
     'フロー制御 ストップアンドウェイト スライディングウィンドウ 輻輳制御',
     '受信ウィンドウと輻輳による制限を区別し、確認応答の遅延が利用率に与える影響を計算しましょう。']],
  [26,'b',
    ['DNS сопоставляет доменные имена с записями, в частности с IP-адресами.',
     'Чтобы обратиться к узлу по имени, приложение запрашивает разрешение имени. DNS-запись A содержит IPv4-адрес, AAAA — IPv6. Ответ может браться из кэша, пока действует его срок хранения. DNS также хранит другие типы записей, поэтому это не просто таблица «одно имя — один адрес»: одному имени могут соответствовать несколько адресов. Выдача адреса устройству относится к DHCP, преобразование частного адреса в публичный — к NAT. DNS помогает найти узел, но сам не вызывает программу на сервере: удалённый вызов выполняет прикладной протокол.',
     'DNS разрешение имён A AAAA DHCP NAT различия',
     'Изучите рекурсивный резолвер, авторитетный сервер, TTL и CNAME. Проследите путь от имени сайта до установления соединения.'],
    ['DNS associates domain names with records, including IP addresses.',
     'An application resolves a name before contacting a host. An A record contains an IPv4 address; AAAA contains IPv6. A cached answer may be reused during its lifetime. DNS has other record types too, and one name may have several addresses. Assigning a device an address is DHCP’s job; translating private and public addresses is NAT’s. DNS helps locate a host, but does not itself invoke a program on that server: an application protocol performs the remote operation.',
     'DNS name resolution A AAAA DHCP NAT differences',
     'Study recursive resolvers, authoritative servers, TTL and CNAME. Trace the steps from a website name to a connection.'],
    ['DNSはドメイン名をレコードに対応付け、IPアドレスの検索にも使われます。',
     'アプリケーションは名前解決を行ってからホストへ接続します。AレコードはIPv4、AAAAはIPv6アドレスを表します。有効期間中はキャッシュを使えることがあります。DNSには他のレコードもあり、一つの名前に複数アドレスが対応する場合もあるため、単純な一対一の表ではありません。端末へのアドレス割当てはDHCP、私用と公開アドレスの変換はNATです。DNSはホストを探しますが、サーバ上のプログラムを呼び出す処理そのものはアプリケーション側のプロトコルが担当します。',
     'DNS 名前解決 A AAAA DHCP NAT 違い',
     '再帰リゾルバ・権威サーバ・TTL・CNAMEと、サイト名から接続までの流れを学びましょう。']],
  [27,'b',
    ['Официальный ответ — LTE, технология широкополосной сотовой связи.',
     'LTE означает Long Term Evolution и относится к сети оператора с базовыми станциями и поддержкой мобильности абонента. IEEE 802.11 — семейство беспроводных локальных сетей, используемое Wi-Fi; NFC предназначен для очень близкого взаимодействия, UWB применяется, например, для точного определения расстояния. Формулировка задачи широкая: телефон действительно может получать широкополосный доступ и через Wi-Fi. Поэтому ориентир для выбора LTE — подразумеваемый контекст мобильной сотовой связи, а не утверждение, что 802.11 вообще не передаёт широкополосные данные. Не запоминайте конкретную скорость LTE: она зависит от конфигурации и условий.',
     'LTE сотовая связь Wi-Fi IEEE 802.11 NFC UWB различия',
     'Сравните базовую станцию и точку доступа, покрытие и handover. Затем изучите различия LTE и 5G NR.'],
    ['The official answer is LTE, a cellular mobile broadband technology.',
     'LTE means Long Term Evolution and uses an operator network with base stations and subscriber mobility. IEEE 802.11 is a wireless LAN family used by Wi-Fi; NFC supports very close-range interaction; UWB is used, for example, for precise ranging. The wording is broad: phones can indeed receive broadband over Wi-Fi. The intended cellular context points to LTE, not a claim that 802.11 cannot carry broadband data. Avoid memorizing a single LTE speed: performance depends on configuration and conditions.',
     'LTE cellular broadband Wi-Fi IEEE 802.11 NFC UWB differences',
     'Compare base stations, access points, coverage and handover. Then study LTE versus 5G NR.'],
    ['公式正解はLTEで、携帯電話網の広帯域通信技術です。',
     'LTEはLong Term Evolutionの略で、基地局や利用者の移動を扱う通信事業者のネットワークです。IEEE 802.11はWi-Fiで使う無線LANの系列、NFCは近接通信、UWBは例えば精密な測距に使われます。問題文は広く、スマートフォンがWi-Fiで広帯域通信することも事実です。LTEを選ぶ根拠は想定されたセルラー通信の文脈であり、802.11が広帯域データを扱えないという意味ではありません。LTEの速度は構成や環境で変わるため、一つの数値だけを暗記しないようにします。',
     'LTE 携帯電話網 Wi-Fi IEEE 802.11 NFC UWB 違い',
     '基地局とアクセスポイント、カバー範囲、ハンドオーバーを比較し、LTEと5G NRも学びましょう。']],
  [28,'c',
    ['Пароль плюс код приложения — два разных фактора: знание и владение устройством с секретом.',
     'Фактор — категория доказательства, а не число экранов входа. Пароль относится к тому, что пользователь знает; приложение с одноразовыми кодами подтверждает владение аутентификатором; биометрия — характеристику человека. Пароль и секретный вопрос остаются одним типом фактора, как и два биометрических признака. Имя пользователя обычно только указывает учётную запись. Два шага не всегда означают MFA. При этом одноразовый код можно выманить фишингом: наличие MFA не делает любой способ входа одинаково устойчивым к атаке.',
     'MFA многофакторная аутентификация знание владение биометрия',
     'Сравните TOTP с устойчивыми к фишингу ключами безопасности и passkeys. Продумайте безопасное восстановление доступа.'],
    ['A password plus an app code combines knowledge with possession of the authenticator’s secret.',
     'A factor is an evidence category, not a login-screen count. Passwords demonstrate knowledge, an OTP app demonstrates possession of an authenticator, and biometrics describe the person. A password plus a security question is still knowledge; two biometric traits remain one category. A username normally identifies the account. Two steps therefore do not necessarily mean MFA. An OTP can still be phished: MFA methods do not all offer equal attack resistance.',
     'MFA authentication knowledge possession inherence TOTP',
     'Compare TOTP with phishing-resistant security keys and passkeys. Study secure account recovery.'],
    ['パスワードとアプリのコードは、知識と認証器の所有という異なる要素です。',
     '要素は証拠の種類で、ログイン画面の数ではありません。パスワードは知識、OTPアプリは認証器の所有、生体情報は本人の特徴です。パスワードと秘密の質問は同じ知識要素で、生体情報二つも同じ分類です。ユーザー名は通常アカウントの識別用です。二段階なら必ずMFAとは限りません。またワンタイムコードもフィッシングで盗まれ得るため、MFAの方式によって耐性は異なります。',
     '多要素認証 知識 所有 生体 TOTP',
     'TOTPとフィッシング耐性のあるセキュリティキーやパスキーを比較し、復旧手順も学びましょう。']],
  [29,'d',
    ['Это целостность (integrity): информация остаётся точной и полной.',
     'Если в платёжном документе незаметно изменили сумму или исчезла строка, нарушена целостность, даже когда документ доступен только нужным людям. Конфиденциальность ограничивает раскрытие, доступность обеспечивает своевременное использование, а аутентификация проверяет заявленную личность или источник. Для контроля целостности используют ограничения базы, права на изменение, журналы и криптографические средства. Обычный хэш помогает обнаружить изменение лишь при доверенном эталоне: если атакующий заменит и файл, и опубликованный рядом хэш, сравнение не спасёт. Подпись или MAC связывают проверку с доверенным ключом.',
     'целостность конфиденциальность доступность CIA integrity хэш MAC подпись',
     'Разберите примеры нарушений каждой части CIA. Сравните контрольную сумму, криптографический хэш, MAC и цифровую подпись.'],
    ['It is integrity: information remains accurate and complete.',
     'An unnoticed amount change or missing line in a payment document violates integrity even if only authorized people can read it. Confidentiality limits disclosure; availability permits timely use; authentication checks a claimed identity or source. Integrity controls include database constraints, write permissions, logs and cryptographic mechanisms. A plain hash detects changes only against a trusted reference: replacing both a file and its nearby published hash defeats that comparison. A signature or MAC ties verification to a trusted key.',
     'CIA integrity confidentiality availability hash MAC digital signature',
     'Classify examples by CIA property. Compare checksums, cryptographic hashes, MACs and digital signatures.'],
    ['完全性です。情報の正確さと完全さを保つ性質を指します。',
     '支払文書の金額が密かに変わったり行が欠けたりすれば、閲覧者が正しく制限されていても完全性の侵害です。機密性は開示の制限、可用性は必要時の利用、認証は本人や発信元の確認です。完全性にはDB制約、変更権限、ログ、暗号学的な仕組みを使います。ただのハッシュ比較には信頼できる基準値が必要です。攻撃者がファイルと隣のハッシュを両方置き換えれば検出できません。署名やMACは信頼する鍵と検証を結び付けます。',
     '完全性 機密性 可用性 CIA ハッシュ MAC 電子署名',
     'CIAの侵害例を分類し、チェックサム・暗号学的ハッシュ・MAC・電子署名を比較しましょう。']],
  [30,'b',
    ['Троян — вредоносная программа, выдающая себя за легитимную или полезную.',
     'Например, установщик «полезной утилиты» может вместе с обещанной функцией скрыто похищать данные. Главный признак здесь — обман относительно назначения программы. Троян не обязан сам размножаться: вирус связывают с заражением другого кода, червь способен распространяться самостоятельно. Категории могут пересекаться: троян способен установить шифровальщик, но эти названия описывают разные признаки. Перебор паролей и расшифровка — возможные действия отдельных инструментов, а не определение трояна; злоумышленник — человек, не программа. Бесплатная лицензия тоже не означает вредоносность.',
     'троян вирус червь вредоносное ПО различия',
     'Изучите происхождение установщиков, цифровые подписи и минимальные привилегии. Различайте способ доставки и вредоносную функцию.'],
    ['A Trojan is malicious software presented as legitimate or useful.',
     'For example, a supposed utility installer may secretly steal data alongside its advertised function. The defining feature is deception about the program’s purpose. Self-replication is not required: viruses infect other code, while worms can propagate independently. Categories can overlap: a Trojan may install ransomware, but those terms describe different features. Password guessing or decryption may be an individual tool’s action, not the definition of a Trojan. A malicious user is a person, not software, and a free license does not imply malware.',
     'Trojan horse virus worm malware differences',
     'Study installer provenance, digital signatures and least privilege. Distinguish delivery methods from malicious payloads.'],
    ['トロイの木馬は、正当または有用なソフトを装う悪意あるプログラムです。',
     '例えば便利なツールのインストーラを装い、説明された機能の裏で情報を盗みます。目的を偽ることが特徴で、自己増殖は必須ではありません。ウイルスは他のコードへの感染、ワームは自律的な拡散で区別します。トロイの木馬がランサムウェアを入れることもあり、名称は別の観点なので重なる場合があります。パスワード総当たりや復号は一部ツールの動作で、定義そのものではありません。悪意ある利用者は人であり、無料ソフトもそれだけでマルウェアではありません。',
     'トロイの木馬 ウイルス ワーム マルウェア 違い',
     '入手元・署名・最小権限と、侵入経路と実行される機能の区別を学びましょう。']],
  [31,'b',
    ['Ransomware блокирует доступ к системе или данным и требует выкуп за восстановление.',
     'Ключевое слово — ransom, выкуп, а не random, случайность. Поэтому генератор случайных чисел и случайный MAC-адрес не подходят. Вымогатель может зашифровать файлы или заблокировать устройство; современные атаки также могут сопровождаться кражей данных и угрозой публикации. Требование денег не гарантирует, что после оплаты доступ вернут. Freeware описывает модель распространения и само по себе не является вредоносным ПО. Для устойчивости важны отдельные защищённые резервные копии и проверенная процедура восстановления: постоянно доступная на запись копия тоже может пострадать.',
     'ransomware программа вымогатель шифровальщик резервное восстановление',
     'Изучите различия блокировщика и шифровальщика, изоляцию резервных копий и проверку восстановления.'],
    ['Ransomware blocks access to systems or data and demands payment to restore it.',
     'Ransom means a payment demand, not randomness. Random-number generation and randomized MAC addresses therefore do not fit. Ransomware may encrypt files or lock a device; attacks may also steal data and threaten disclosure. A demand does not guarantee that paying restores access. Freeware is a distribution model, not inherently malware. Resilience needs separate protected backups and tested recovery: a continuously writable backup may also be damaged.',
     'ransomware locker encryptor backup recovery',
     'Compare lockers and encryptors. Study isolated backups and restore testing.'],
    ['ランサムウェアはシステムやデータへのアクセスを妨げ、復旧のために身代金を要求します。',
     'ransomは身代金で、randomとは別です。乱数生成やMACアドレスのランダム化は該当しません。ファイル暗号化や端末ロックのほか、データ窃取と公開の脅迫を伴う場合もあります。支払っても復旧は保証されません。フリーウェアは配布形態で、それ自体がマルウェアではありません。対策には独立して保護したバックアップと復旧試験が重要で、常時書込み可能なコピーは一緒に被害を受け得ます。',
     'ランサムウェア 身代金 暗号化 バックアップ 復旧',
     'ロック型と暗号化型、バックアップの隔離、復旧試験を学びましょう。']],
  [32,'b',
    ['Это избегание риска: компания исключила функцию, создающую конкретный риск раскрытия публикаций.',
     'Сравните действие компании, а не только её намерение повысить безопасность. Она не оставила плагин с дополнительной проверкой, а решила его не включать. Это прекращение рискованной деятельности — avoidance. Исправить настройки приватности и протестировать плагин было бы снижением риска, mitigation. Оставить известную проблему с осознанным решением принять последствия — acceptance. Разделить часть последствий с партнёром или страховщиком — sharing. Исключение плагина устраняет этот путь утечки, но не все риски игры; у решения также есть цена — потерянная возможность публикаций.',
     'обработка риска избегание снижение принятие разделение risk avoidance',
     'Для одного риска придумайте четыре способа реагирования. Оцените остаточный риск и затраты каждого решения.'],
    ['This is risk avoidance: the company removes the feature causing this specific disclosure risk.',
     'Classify the action, not merely the intention to improve security. The company does not retain the plugin with more checks; it decides not to include it. Stopping the risky activity is avoidance. Fixing privacy handling and testing the plugin would mitigate the risk. Deliberately retaining the known issue and accepting its consequences is acceptance. Allocating consequences with a partner or insurer is sharing. Removing this plugin eliminates that exposure route, not every game risk, and sacrifices the posting feature.',
     'risk response avoidance mitigation acceptance sharing residual risk',
     'Propose four responses to one risk and compare costs and residual exposure.'],
    ['リスク回避です。公開範囲の問題を生む機能自体を採用しないと決めています。',
     '安全性を上げたいという目的だけでなく、実際の行動を分類します。検査を追加して使うのではなく、プラグインを外すので回避です。設定処理の修正と試験なら低減、既知の問題を理解した上で残すなら受容、相手企業や保険などと結果の負担を分けるなら共有です。機能除去でこの漏えい経路はなくなりますが、ゲーム全体の全リスクが消えるわけではありません。また投稿機能を失うという費用もあります。',
     'リスク対応 回避 低減 受容 共有 残留リスク',
     '同じリスクに四つの対応を考え、費用と残るリスクを比較しましょう。']],
  [33,'a',
    ['CSIRT — команда реагирования на инциденты информационной безопасности.',
     'Команда принимает сообщения, выясняет масштаб инцидента и координирует реагирование. Например, сообщение о подозрительной учётной записи нужно оценить, связать с журналами, ограничить последствия и организовать восстановление с ответственными подразделениями. CSIRT — не просто антивирус и не обязательно один отдел: важны полномочия и взаимодействие специалистов. SOC обычно сосредоточен на мониторинге и обнаружении, хотя задачи команд могут пересекаться. Стандартизация интернет-протоколов и глобальная координация имён и адресов — другие функции, а политическая мотивация не определяет CSIRT.',
     'CSIRT команда реагирования инцидент SOC роли',
     'Изучите приём и оценку инцидента, сдерживание, восстановление и разбор причин. Определите роли ИТ, безопасности и владельца сервиса.'],
    ['A CSIRT is a computer security incident response team.',
     'It receives reports, investigates scope and coordinates response. A suspicious-account report may require assessment, log correlation, containment and recovery with the responsible departments. A CSIRT is not merely antivirus software or necessarily a single department: authority and coordination matter. A SOC generally emphasizes monitoring and detection, although responsibilities can overlap. Internet-protocol standardization and global naming/address coordination are different functions. Political motivation does not define a CSIRT.',
     'CSIRT incident response team SOC roles coordination',
     'Study triage, containment, recovery and lessons learned. Identify the roles of IT, security and the service owner.'],
    ['CSIRTはコンピュータセキュリティインシデントに対応するチームです。',
     '報告の受付、影響範囲の調査、対応の調整を行います。不審なアカウントの報告なら、評価、ログ照合、被害拡大の抑制、担当部門と連携した復旧などが必要です。単なるウイルス対策ソフトではなく、一つの部署とは限りません。権限と連携が重要です。SOCは通常監視・検知を中心としますが役割は重なる場合もあります。インターネットの標準化や名前・アドレスの世界的調整は別の仕事で、政治的目的もCSIRTの定義ではありません。',
     'CSIRT インシデント対応 SOC 役割 連携',
     'トリアージ・封じ込め・復旧・振返りと、IT・セキュリティ・サービス責任者の分担を学びましょう。']],
  [34,'c',
    ['Первый оператор выбирает все строки accounts, второй удаляет саму таблицу accounts.',
     'Условие WHERE имеет вид username=… OR истинное выражение: сравнение строки 1 с самой собой всегда истинно. Поэтому отбор не ограничивается пользователем 1. Точка с запятой завершает SELECT; далее идёт отдельный DROP TABLE, который удаляет таблицу, а не только остальные строки. Задача прямо говорит, что оба оператора выполнены; в реальном приложении это зависит от поддержки нескольких операторов и прав подключения. Не запускайте пример на рабочей базе. Причина SQL-инъекции — смешение пользовательских данных с текстом команды. Параметризованные запросы разделяют эти роли, а минимальные права ограничивают последствия.',
     'SQL injection параметризованные запросы OR DROP TABLE SELECT',
     'Сравните DROP TABLE, DELETE и TRUNCATE в учебной базе. Изучите подготовленные запросы и запрет лишних прав приложению.'],
    ['The first statement selects every accounts row; the second removes the accounts table itself.',
     'The WHERE clause combines a username test with an always-true string equality using OR. It therefore does not restrict selection to user 1. A semicolon ends SELECT, followed by a separate DROP TABLE, not deletion of just the other rows. The question states that both execute; real applications depend on multi-statement support and connection privileges. Do not run the example against a live database. Injection arises when user data becomes SQL command text. Parameterized queries separate data from commands, while least privilege limits damage.',
     'SQL injection parameterized queries OR DROP TABLE SELECT',
     'Compare DROP TABLE, DELETE and TRUNCATE in a practice database. Study prepared statements and least-privileged application accounts.'],
    ['最初の文はaccountsの全行を選択し、次の文はaccounts表そのものを削除します。',
     'WHEREはユーザー名の条件と常に真の文字列比較をORで結ぶため、ユーザー1だけには絞れません。セミコロンでSELECTが終わり、別のDROP TABLEが続きます。これは他の行だけの削除ではありません。本問は両文が実行されたとしていますが、実際には複数文の許可や接続権限に依存します。本番DBで実行しないでください。SQLインジェクションは入力データがSQL命令の一部になることで起きます。パラメータ化でデータと命令を分け、最小権限で被害を抑えます。',
     'SQLインジェクション パラメータ化 OR DROP TABLE SELECT',
     '練習用DBでDROP TABLE・DELETE・TRUNCATEの違いを学び、プリペアド文と最小権限も確認しましょう。']],
  [35,'d',
    ['Подходит диаграмма вариантов использования: внешние участники и цели их взаимодействия с системой.',
     'Для интернет-магазина актор «покупатель» связан с вариантами использования «оформить заказ» и «посмотреть доставку». Актором может быть и другая система, не только человек. Граница системы помогает показать, что находится внутри рассматриваемой области. Связи include и extend уточняют отношения вариантов использования, но не являются временной последовательностью шагов. Диаграмма деятельности описывает поток действий, communication — взаимодействия объектов через сообщения, interaction overview — обзор потока взаимодействий. Для условий этого вопроса важнее всего акторы и доступные им функции, а не внутренний алгоритм.',
     'UML use case диаграмма вариантов использования актор include extend',
     'Нарисуйте акторов своего приложения и их цели. Дополните один сценарий текстом и диаграммой деятельности, не смешивая уровни.'],
    ['Use a use case diagram: it shows external actors and their goals when interacting with the system.',
     'For a shop, the customer actor can connect to Place order and Track delivery. An actor may also be another system, not just a person. The system boundary clarifies scope. Include and extend express use-case relationships, not a chronological sequence. An activity diagram models action flow, a communication diagram models object messages, and an interaction overview organizes interaction flow. This question emphasizes actors and available functions rather than the internal algorithm.',
     'UML use case diagram actors system boundary include extend',
     'Draw your application’s actors and goals. Expand one use case into prose and an activity diagram without mixing abstraction levels.'],
    ['ユースケース図です。外部のアクターと、システムを使って達成する目的を表します。',
     '通販なら購入者というアクターを「注文する」「配送を確認する」に結びます。アクターは人だけでなく他のシステムでも構いません。システム境界で対象範囲を示します。includeやextendはユースケース間の関係で、時系列の手順ではありません。アクティビティ図は動作の流れ、コミュニケーション図はオブジェクト間のメッセージ、相互作用概要図は相互作用の流れを扱います。本問の中心は内部アルゴリズムよりアクターと機能です。',
     'UML ユースケース図 アクター システム境界 include extend',
     'アプリのアクターと目的を描き、一つを文章やアクティビティ図で詳しく表しましょう。']],
  [36,'a',
    ['Adapter преобразует один интерфейс в другой, ожидаемый клиентом, чтобы несовместимые классы могли сотрудничать.',
     'Пример: приложение ждёт метод send(message), а библиотека предоставляет deliver(text, destination). Адаптер реализует send и внутри вызывает deliver, преобразовав параметры и результат. Клиент продолжает работать со своим интерфейсом, а существующая библиотека не требует переписывания. Это структурный шаблон — он организует взаимодействие компонентов. Factory решает создание объектов, Iterator — последовательный доступ к элементам, Singleton — ограничение числа экземпляров. Адаптер не исправляет несовместимый смысл операций автоматически: корректное сопоставление параметров и поведения нужно спроектировать.',
     'паттерн Adapter адаптер несовместимые интерфейсы композиция',
     'Напишите адаптер для двух учебных API. Сравните его с Facade и Decorator: упрощение интерфейса и добавление поведения решают другие задачи.'],
    ['Adapter converts an existing interface into the one a client expects, enabling incompatible classes to cooperate.',
     'Suppose an application expects send(message), while a library offers deliver(text, destination). An adapter implements send and delegates to deliver with mapped parameters and results. The client keeps its interface and the library need not be rewritten. This is a structural pattern organizing component collaboration. Factory concerns object creation, Iterator traverses a collection, and Singleton limits instances. An adapter cannot automatically repair incompatible semantics: the mapping of parameters and behaviour must still be designed correctly.',
     'Adapter design pattern incompatible interfaces composition',
     'Write an adapter for two practice APIs. Compare Facade and Decorator: simplifying an interface and adding behaviour are different goals.'],
    ['Adapterです。既存のインターフェースをクライアントが期待する形へ変換します。',
     'アプリがsend(message)を要求し、ライブラリがdeliver(text, destination)を提供する場合、アダプタがsendを実装して引数や結果を対応付けてdeliverを呼びます。クライアントも既存ライブラリも大きく書き換えず連携できます。構造に関するパターンです。Factoryは生成、Iteratorは要素の巡回、Singletonはインスタンス数の制限を扱います。ただし処理の意味の不一致まで自動解決するわけではなく、引数や振る舞いの対応を正しく設計する必要があります。',
     'Adapter パターン アダプタ インターフェース 互換性',
     '二つの練習用APIを適合させ、Facadeの単純化とDecoratorの振る舞い追加との違いを学びましょう。']],
  [37,'b',
    ['Инкапсуляция объединяет состояние и операции над ним, скрывая внутреннюю реализацию за интерфейсом.',
     'У счёта можно скрыть balance и разрешить изменение через deposit и withdraw. Тогда withdraw проверит допустимость операции, а внешний код не сможет случайно присвоить произвольное значение в обход правил. Суть не в механическом добавлении getter/setter: открытый setter без проверки тоже может разрушить инвариант. Объединение похожих свойств в общий класс связано с абстракцией и обобщением; получение свойств базового класса — с наследованием. Инкапсуляция уменьшает зависимость клиента от деталей: внутреннее хранение можно изменить, сохранив обещанное поведение интерфейса.',
     'ООП инкапсуляция сокрытие реализации инвариант интерфейс',
     'Спроектируйте объект с проверяемым инвариантом. Сравните инкапсуляцию, абстракцию, наследование и полиморфизм.'],
    ['Encapsulation bundles state with its operations and hides implementation behind an interface.',
     'An account can hide balance and expose deposit and withdraw. Withdraw checks the rules, while callers cannot accidentally assign arbitrary values that bypass them. Merely adding getters and setters is not enough: an unchecked setter may still break an invariant. Extracting shared properties relates to abstraction and generalization; acquiring base-class properties relates to inheritance. Encapsulation reduces client dependence on internals, allowing storage details to change while the interface’s promised behaviour remains stable.',
     'OOP encapsulation information hiding invariant interface',
     'Design an object with a checked invariant. Compare encapsulation, abstraction, inheritance and polymorphism.'],
    ['カプセル化は状態と操作をまとめ、インターフェースの内側に実装を隠します。',
     '口座のbalanceを隠し、depositとwithdrawだけで変更できるようにします。withdrawが規則を検査し、外部から不正な値を直接設定することを防ぎます。getter/setterを付けるだけでは不十分で、無検査のsetterは不変条件を壊せます。共通性の抽出は抽象化や汎化、基底クラスの性質を受け継ぐのは継承です。カプセル化により呼出側が内部構造に依存しにくくなり、インターフェースの約束を保って保存方法などを変更できます。',
     'カプセル化 情報隠蔽 不変条件 インターフェース',
     '不変条件を検査するオブジェクトを設計し、抽象化・継承・多態性と比較しましょう。']],
  [38,'a',
    ['Это адаптивное сопровождение: систему приспосабливают к изменившейся среде, например новой ОС или СУБД.',
     'Старая функция приложения могла быть корректной, но после смены API операционной системы ей нужен другой вызов. Причина изменения — внешняя среда, поэтому категория adaptive. Corrective исправляет обнаруженную ошибку. Perfective улучшает, например, производительность или удобство сопровождения. Preventive устраняет потенциальные причины будущих отказов до их проявления. Классифицируйте по цели: одна техническая операция, например переписывание модуля, может относиться к разным категориям. В этой задаче явно указана смена программного окружения, а не новый пользовательский сценарий.',
     'сопровождение ПО adaptive corrective perfective preventive',
     'Придумайте четыре изменения одного приложения и классифицируйте по причине. Изучите регрессионные тесты после обновления зависимостей.'],
    ['It is adaptive maintenance: adjusting software to a changed environment such as a new OS or DBMS.',
     'An application function may have been correct but need a different call after an operating-system API changes. The driver is the environment, so the maintenance is adaptive. Corrective maintenance fixes a discovered defect. Perfective maintenance improves qualities such as performance or maintainability. Preventive maintenance removes potential causes of future failures before they manifest. Classify by purpose: rewriting a module can belong to different categories. This question explicitly concerns the software environment rather than a new user workflow.',
     'software maintenance adaptive corrective perfective preventive',
     'Classify four changes to one application by their purpose. Study regression tests after dependency upgrades.'],
    ['適応保守です。OSやDBMSなどの環境変化にソフトウェアを合わせます。',
     'もともと正しかった機能でも、OSのAPIが変われば別の呼出しが必要になります。原因が環境変化なのでadaptiveです。correctiveは発見済みの不具合修正、perfectiveは性能や保守性などの改善、preventiveは将来の故障原因を顕在化前に取り除く保守です。同じモジュールの書換えでも目的によって分類が変わります。本問は新しい利用シナリオではなく、ソフトウェア環境の変更を明示しています。',
     'ソフトウェア保守 適応 是正 完全化 予防',
     '一つのアプリの変更を四つ考えて目的で分類し、依存関係更新後の回帰試験も学びましょう。']],
  [39,'a',
    ['Подходит Agile: короткие циклы разработки с частой обратной связью и адаптацией приоритетов.',
     'Команда может сначала выпустить небольшой рабочий сценарий профиля и публикации, получить отзывы, затем скорректировать рекомендации и следующие задачи. Важны полезные приращения продукта и повторная проверка предположений, а не ожидание полной готовности всех модулей. Прототипирование помогает исследовать неопределённость и может применяться внутри Agile, но само по себе не задаёт весь процесс постоянного развития. Спиральная модель выделяет работу с рисками, каскадная — последовательные стадии. Agile не означает отсутствие документации, архитектуры и тестирования, а размер команды сам по себе не гарантирует гибкость.',
     'Agile итеративная инкрементальная разработка обратная связь',
     'Сравните итерацию и инкремент, Scrum и Kanban. Разбейте функцию на маленькие проверяемые пользовательские результаты.'],
    ['Agile fits: short development cycles with frequent feedback and reprioritization.',
     'A team might release a small usable profile-and-sharing workflow, gather feedback, then adjust recommendations and upcoming work. Useful increments and repeated validation matter more than waiting until every module is complete. Prototyping explores uncertainty and can be part of Agile, but alone does not define ongoing product development. Spiral emphasizes risk analysis; waterfall emphasizes sequential phases. Agile does not mean no documentation, architecture or testing, and small team size alone does not make a process agile.',
     'Agile iterative incremental development feedback',
     'Compare iterations with increments and Scrum with Kanban. Split a feature into small testable user outcomes.'],
    ['Agileが適しています。短い開発周期で反応を集め、優先順位を調整します。',
     '例えばプロフィールと共有の小さな実用シナリオを出し、反応を基に推薦機能や次の作業を調整します。全モジュール完成まで待つより、使える増分と仮説の繰返し検証を重視します。プロトタイピングは不確実性の調査に有効でAgileでも使えますが、それだけで継続的開発全体を定義しません。スパイラルはリスク分析、ウォーターフォールは段階的進行を重視します。Agileは文書・設計・テスト不要という意味ではなく、小人数だけでも決まりません。',
     'アジャイル 反復 増分開発 フィードバック',
     '反復と増分、ScrumとKanbanを比較し、機能を小さな検証可能な利用成果に分けましょう。']],
  [40,'c',
    ['Высший уровень зрелости CMMI — 5, Optimizing: постоянное улучшение процессов на основе данных.',
     'Различайте измерение и улучшение. На уровне 4, Quantitatively managed, процессом управляют количественно и анализируют его вариабельность. Уровень 5 использует эту основу для систематических улучшений и предотвращения повторяющихся причин проблем. Например, команда не просто измеряет долю дефектов, а проверяет изменение процесса и оценивает его эффект. Defined — уровень 3, Managed — 2; их наличие ещё не означает высшую зрелость. Высокий уровень не гарантирует отсутствие ошибок в каждом продукте. Вопрос о maturity level организации, а не об отдельном показателе качества кода.',
     'CMMI maturity levels 5 Optimizing 4 Quantitatively managed',
     'Сравните стандартный процесс, количественное управление и непрерывное улучшение. Придумайте измеримый эксперимент улучшения процесса.'],
    ['The highest CMMI maturity level is 5, Optimizing: continual, evidence-based process improvement.',
     'Distinguish measurement from improvement. Level 4, Quantitatively managed, uses quantitative control and analyzes process variation. Level 5 builds on that foundation to improve systematically and address recurring causes. For example, a team measures defects, tests a process change and evaluates its effect rather than merely collecting counts. Defined is level 3 and Managed level 2. High maturity does not guarantee a defect-free product. The question concerns organizational maturity, not an individual code-quality metric.',
     'CMMI maturity levels optimizing quantitatively managed',
     'Compare standardized processes, quantitative management and continual improvement. Design a measurable process-improvement experiment.'],
    ['CMMIの最高成熟度はレベル5、Optimizingです。データに基づく継続的改善を重視します。',
     '測定と改善を区別します。レベル4のQuantitatively managedは定量管理とプロセス変動の分析を行います。5ではその基盤を使って体系的に改善し、問題の繰返し原因に対処します。例えば欠陥数を記録するだけでなく、工程の変更を試して効果を測ります。Definedは3、Managedは2で、それだけでは最高段階ではありません。成熟度が高くても個々の製品の無欠陥を保証しません。問われているのは組織の成熟度で、単独のコード品質指標ではありません。',
     'CMMI 成熟度レベル5 最適化 定量管理',
     '標準化・定量管理・継続的改善を比較し、効果を測定できる工程改善実験を考えましょう。']],
];

const sources:Record<number,{title:string;url:string}[]>={
  22:[{title:'PostgreSQL · LIKE patterns',url:'https://www.postgresql.org/docs/current/functions-matching.html'}],
  24:[{title:'RFC 3022 · NAT / NAPT',url:'https://www.rfc-editor.org/rfc/rfc3022'}],
  26:[{title:'RFC 1034 · Domain names',url:'https://www.rfc-editor.org/rfc/rfc1034'}],
  28:[{title:'NIST · Multi-factor authentication',url:'https://csrc.nist.gov/glossary/term/multi_factor_authentication'}],
  33:[{title:'FIRST · CSIRT services',url:'https://www.first.org/standards/frameworks/csirts/csirt_services_framework_v2.1'}],
  34:[{title:'OWASP · SQL injection prevention',url:'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'}],
  39:[{title:'Agile Manifesto · Principles',url:'https://agilemanifesto.org/principles.html'}],
  40:[{title:'CMMI Institute · Maturity levels',url:'https://cmmiinstitute.com/learning/appraisals/levels'}],
  3:[{title:'MIT OCW · Queue utilization',url:'https://ocw.mit.edu/courses/2-852-manufacturing-systems-analysis-spring-2010/762d5fe93efddca9c0f9a7bcf82b737b_MIT2_852S10_probability.pdf'}],
  4:[{title:'MDN · Regex quantifiers',url:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Quantifier'}],
  12:[{title:'IBM · RAID levels',url:'https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-bm-raid-levels'}],
  16:[{title:'GCC · Linking',url:'https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html'}],
  19:[{title:'PostgreSQL · SELECT ALL / DISTINCT',url:'https://www.postgresql.org/docs/17/sql-select.html'}],
  20:[{title:'Microsoft · Database normalization',url:'https://learn.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description'}],
};
export function feLesson(part:string|undefined,number:number,language:'ru'|'en'|'ja'){
  if(part!=='A')return null;
  const entry=feLessonEntries.find(item=>item[0]===number);
  if(!entry)return null;
  const [core,detail,search,next]=entry[language==='ru'?2:language==='en'?3:4];
  return {core,detail,search,next,sources:sources[number]};
}
