export type UiLanguage = 'ru' | 'en' | 'ja';

export type Lesson = { core: string; method: string; example: string; pitfall: string };

export const uiCopy = {
  ru: {
    home: 'На главную', badge: 'Подготовка по официальному формату', heroA: 'Выберите свой маршрут', heroB: 'к уверенной сдаче.', intro: 'Практика по структуре ITPEC и IPA. Ошибки превращаются в понятный учебный разбор.',
    system: 'Система экзамена', level: 'Уровень', year: 'Год экзамена', mode: 'Режим', examLanguage: 'Язык настоящего экзамена', english: 'английский', japanese: 'японский', onePart: 'Одна непрерывная часть',
    learn: 'Обучение', learnDesc: 'Ответ и учебный разбор появляются сразу', mock: 'Пробный экзамен', mockDesc: 'Без таймера и подсказок, итог в конце', exam: 'Экзамен', examDesc: 'С таймером, без подсказок, итог в конце',
    session: 'Ваша сессия', verified: 'Проверенный формат', localProgress: 'Локальный прогресс', answers: 'ответов', correctShort: 'верных', examsByYear: 'Экзамены по годам', attempts: 'попыток', best: 'лучший', notTaken: 'ещё не пройден', passed: 'Успешно', available: 'проверочных вопросов', start: 'Начать сессию',
    question: 'Вопрос', of: 'из', questionLanguage: 'Язык вопроса', original: 'Оригинал', russian: 'Русский', interface: 'Интерфейс', exit: 'Выйти', next: 'Дальше', finishA: 'Завершить A', results: 'К результату',
    correct: 'Верно', wrong: 'Пока неверно', quickReason: 'Короткий ответ', learnTopic: 'Изучить тему подробно', principle: 'Принцип', method: 'Как решать', example: 'Разобранный пример', pitfall: 'Типичная ошибка', remember: 'Запомнить',
    partDone: 'Часть A завершена', breakText: 'Перед частью B можно сделать перерыв. Ответы части A сохранены и изменить их уже нельзя.', officialBreak: 'Официальный максимум — 10 минут.', organizerBreak: 'ITPEC не задаёт единую длительность перерыва: следуйте правилам организатора.', breakLeft: 'Осталось перерыва', untimedBreak: 'Пауза без таймера', startB: 'Начать часть B',
    sessionDone: 'Сессия завершена', examPassed: 'Экзамен пройден', thresholdMissed: 'Порог не достигнут', learnDone: 'Вы разобрали ответы. Повторите темы с низким результатом после короткого перерыва.', ipRule: 'В MVP успешным считается результат от 60%. Официальная оценка IP дополнительно требует порога по каждой области.', feRule: 'Для успешного FE нужно не менее 60% отдельно в каждой части',
    fullReview: 'Полный разбор', reviewTitle: 'Что было отвечено и где ошибка', errors: 'ошибок', noAnswer: 'нет ответа', error: 'ошибка', yourAnswer: 'Ваш ответ', correctAnswer: 'Правильный ответ', answerMissing: 'Ответ не выбран', back: 'К настройке', retry: 'Пройти ещё раз', technology: 'Технологии', management: 'Управление', strategy: 'Стратегия', source: 'Учебная адаптация',
  },
  en: {
    home: 'Home', badge: 'Official-format preparation', heroA: 'Choose your route', heroB: 'to a confident pass.', intro: 'Practice for ITPEC and IPA. Every mistake becomes a clear learning review.',
    system: 'Exam system', level: 'Level', year: 'Exam year', mode: 'Mode', examLanguage: 'Actual exam language', english: 'English', japanese: 'Japanese', onePart: 'One continuous section',
    learn: 'Learn', learnDesc: 'Answer and lesson appear immediately', mock: 'Mock exam', mockDesc: 'No timer or hints; results at the end', exam: 'Exam', examDesc: 'Timed, no hints; results at the end',
    session: 'Your session', verified: 'Verified format', localProgress: 'Local progress', answers: 'answers', correctShort: 'correct', examsByYear: 'Exams by year', attempts: 'attempts', best: 'best', notTaken: 'not attempted', passed: 'Passed', available: 'practice questions', start: 'Start session',
    question: 'Question', of: 'of', questionLanguage: 'Question language', original: 'Original', russian: 'Russian', interface: 'Interface', exit: 'Exit', next: 'Next', finishA: 'Finish A', results: 'View results',
    correct: 'Correct', wrong: 'Not quite', quickReason: 'Short answer', learnTopic: 'Study the topic', principle: 'Principle', method: 'How to solve', example: 'Worked example', pitfall: 'Common mistake', remember: 'Remember',
    partDone: 'Subject A completed', breakText: 'You may take a break before Subject B. Subject A answers are saved and cannot be changed.', officialBreak: 'Official maximum: 10 minutes.', organizerBreak: 'ITPEC does not define one common break duration; follow your local organizer.', breakLeft: 'Break remaining', untimedBreak: 'Untimed break', startB: 'Start Subject B',
    sessionDone: 'Session complete', examPassed: 'Exam passed', thresholdMissed: 'Threshold not reached', learnDone: 'You reviewed the answers. Revisit weaker topics after a short break.', ipRule: 'In this MVP, 60% is treated as a pass. Official IP scoring also applies a threshold to every field.', feRule: 'To pass FE, score at least 60% in each subject',
    fullReview: 'Full review', reviewTitle: 'Your answers and mistakes', errors: 'errors', noAnswer: 'unanswered', error: 'incorrect', yourAnswer: 'Your answer', correctAnswer: 'Correct answer', answerMissing: 'No answer selected', back: 'Back to setup', retry: 'Try again', technology: 'Technology', management: 'Management', strategy: 'Strategy', source: 'Learning adaptation',
  },
  ja: {
    home: 'ホーム', badge: '公式形式に沿った試験対策', heroA: '自分に合った学習ルートで', heroB: '合格を目指しましょう。', intro: 'ITPEC・IPA形式で練習し、間違いを分かりやすい教材として復習できます。',
    system: '試験制度', level: 'レベル', year: '試験年度', mode: 'モード', examLanguage: '実際の試験言語', english: '英語', japanese: '日本語', onePart: '連続した1科目',
    learn: '学習', learnDesc: '解答後すぐに教材を表示', mock: '模擬試験', mockDesc: '時間制限・ヒントなし、最後に結果表示', exam: '試験', examDesc: '時間制限あり、ヒントなし、最後に結果表示',
    session: 'セッション', verified: '確認済みの形式', localProgress: '端末内の進捗', answers: '解答', correctShort: '正解', examsByYear: '年度別の結果', attempts: '回', best: '最高', notTaken: '未受験', passed: '合格', available: '問の練習問題', start: '開始',
    question: '問題', of: '/', questionLanguage: '問題の言語', original: '原文', russian: 'ロシア語', interface: '画面言語', exit: '終了', next: '次へ', finishA: '科目Aを終了', results: '結果を見る',
    correct: '正解', wrong: '不正解', quickReason: '要点', learnTopic: '詳しく学ぶ', principle: '原理', method: '解き方', example: '例題', pitfall: 'よくある誤り', remember: '覚えること',
    partDone: '科目Aが終了しました', breakText: '科目Bの前に休憩できます。科目Aの解答は保存され、変更できません。', officialBreak: '公式の上限は10分です。', organizerBreak: 'ITPEC共通仕様では休憩時間が統一されていません。実施機関の案内に従ってください。', breakLeft: '残り休憩時間', untimedBreak: '時間制限なし', startB: '科目Bを開始',
    sessionDone: '学習完了', examPassed: '合格', thresholdMissed: '基準未達', learnDone: '解答を復習しました。苦手分野をもう一度確認しましょう。', ipRule: 'このMVPでは60%以上を合格とします。実際のIP試験では分野別の基準もあります。', feRule: 'FE合格には科目A・Bの両方で60%以上が必要です',
    fullReview: '全問レビュー', reviewTitle: '解答と間違いを確認', errors: '問不正解', noAnswer: '未回答', error: '不正解', yourAnswer: 'あなたの解答', correctAnswer: '正解', answerMissing: '未回答', back: '設定へ戻る', retry: 'もう一度', technology: 'テクノロジ', management: 'マネジメント', strategy: 'ストラテジ', source: '学習用アレンジ',
  },
} as const;

export const topicLabels: Record<string, Record<UiLanguage, string>> = {
  'Логика': { ru: 'Логика', en: 'Logic', ja: '論理演算' }, 'Системы счисления': { ru: 'Системы счисления', en: 'Number systems', ja: '数値表現' }, 'Архитектура компьютера': { ru: 'Архитектура компьютера', en: 'Computer architecture', ja: 'コンピュータ構成' }, 'Управление проектами': { ru: 'Управление проектами', en: 'Project management', ja: 'プロジェクト管理' }, 'Финансы': { ru: 'Финансы', en: 'Finance', ja: '財務' }, 'Производительность': { ru: 'Производительность', en: 'Performance', ja: '性能' }, 'Базы данных': { ru: 'Базы данных', en: 'Databases', ja: 'データベース' }, 'Сложность алгоритмов': { ru: 'Сложность алгоритмов', en: 'Algorithm complexity', ja: '計算量' }, 'Аутентификация': { ru: 'Аутентификация', en: 'Authentication', ja: '認証' }, 'Структуры данных': { ru: 'Структуры данных', en: 'Data structures', ja: 'データ構造' }, 'Сети': { ru: 'Сети', en: 'Networks', ja: 'ネットワーク' },
};

const L = (ru: Lesson, en: Lesson, ja: Lesson) => ({ ru, en, ja });
export const lessons: Record<string, Record<UiLanguage, Lesson>> = {
  'ip-logic-and': L(
    { core: 'AND даёт 1 только при двух единицах на входе.', method: 'Составьте таблицу для 00, 01, 10 и 11. Сравните строку, где функция должна стать истинной.', example: '1 AND 1 = 1, но 1 AND 0 = 0. Поэтому условию «оба» соответствует AND.', pitfall: 'OR означает «хотя бы один», а XOR — «ровно один». Эти формулировки нельзя смешивать.' },
    { core: 'AND outputs 1 only when both inputs are 1.', method: 'Write the four input pairs 00, 01, 10 and 11, then mark where the required function is true.', example: '1 AND 1 = 1, while 1 AND 0 = 0. The word “both” points to AND.', pitfall: 'OR means “at least one”; XOR means “exactly one”.' },
    { core: 'ANDは両方の入力が1のときだけ1になります。', method: '00、01、10、11の真理値表を作り、条件が真になる行を確認します。', example: '1 AND 1 = 1、1 AND 0 = 0です。「両方」がANDの手掛かりです。', pitfall: 'ORは「少なくとも一方」、XORは「ちょうど一方」です。' }),
  'ip-binary-155': L(
    { core: 'Двоичное число — сумма степеней двойки. Справа налево разряды имеют веса 1, 2, 4, 8, 16, 32, 64, 128…', method: 'Для перевода из двоичной системы в десятичную подпишите веса разрядов и сложите только те, над которыми стоит 1. Для обратного перевода последовательно выбирайте наибольшие степени двойки, не превышающие остаток.', example: '10011011₂ = 1×128 + 0×64 + 0×32 + 1×16 + 1×8 + 0×4 + 1×2 + 1×1 = 155₁₀. Обратно: 155−128=27, −16=11, −8=3, −2=1, −1=0.', pitfall: 'Не читайте двоичную запись как обычное десятичное число. Вес позиции удваивается при каждом шаге влево.' },
    { core: 'A binary number is a sum of powers of two. From right to left the place values are 1, 2, 4, 8, 16, 32, 64, 128…', method: 'Binary to decimal: label each bit with its place value and add values whose bit is 1. Decimal to binary: repeatedly subtract the largest power of two that fits.', example: '10011011₂ = 128 + 16 + 8 + 2 + 1 = 155₁₀. In reverse, these selected powers become 1-bits.', pitfall: 'Do not read binary digits as a decimal number; every step left doubles the place value.' },
    { core: '2進数は2の累乗の和です。右から位の重みは1、2、4、8、16、32、64、128…です。', method: '10進数へは、1のビットに対応する重みだけを加算します。2進数へは、残り以下の最大の2の累乗を順に選びます。', example: '10011011₂ = 128 + 16 + 8 + 2 + 1 = 155₁₀です。', pitfall: '2進数を10進数の桁として読まないでください。左へ1桁進むごとに重みは2倍です。' }),
  'ip-cache': L(
    { core: 'Кэш хранит небольшую рабочую часть данных ближе к процессору и уменьшает среднюю задержку.', method: 'Разделяйте иерархию по скорости, объёму и назначению: кэш быстрее и меньше RAM; RAM быстрее накопителя, но энергозависима.', example: 'Если программа повторно читает одну область массива, она с высокой вероятностью уже находится в кэше.', pitfall: 'Кэш не заменяет RAM и не предназначен для постоянного хранения файлов.' },
    { core: 'Cache keeps a small working set close to the CPU and reduces average latency.', method: 'Compare memory levels by speed, capacity and persistence: cache is faster and smaller than RAM.', example: 'Repeated access to a nearby array region is likely served from cache because of locality.', pitfall: 'Cache neither replaces RAM nor stores files permanently.' },
    { core: 'キャッシュはCPUの近くに小さな作業データを保持し、平均アクセス時間を短縮します。', method: '速度・容量・永続性で階層を比較します。キャッシュは主記憶より高速で小容量です。', example: '配列の近い要素を繰り返し読むと、局所性によりキャッシュから読める可能性が高まります。', pitfall: 'キャッシュは主記憶の代替でも、ファイルの永続保存場所でもありません。' }),
  'ip-wbs': L(
    { core: 'WBS описывает полный состав результатов и работ проекта в виде иерархии.', method: 'WBS (Work Breakdown Structure, иерархическая структура работ) последовательно разбивает весь объём проекта от конечного результата до небольших управляемых пакетов работ. Такая декомпозиция помогает проверить полноту проекта, распределить ответственность, а затем оценить трудозатраты, стоимость и длительность каждого пакета.', example: 'Например, результат «веб-сайт» можно разделить на дизайн, разработку и контент, а разработку — на авторизацию, каталог и оплату. На нижнем уровне должен получиться пакет, которому можно назначить ответственного и критерий готовности.', pitfall: 'Главное различие: WBS отвечает «что должно быть сделано». Расписание отвечает «когда», бюджет — «сколько стоит», а реестр рисков — «что может помешать».' },
    { core: 'A WBS is a hierarchical decomposition of all project deliverables and work.', method: 'A Work Breakdown Structure decomposes the entire project scope from the final deliverable into small, manageable work packages. This helps verify that no required work is missing, assign ownership, and later estimate effort, cost and duration for each package.', example: 'For a website, the first level might contain design, development and content; development can then split into authentication, catalogue and payments. A lowest-level package should be assignable and have a clear completion criterion.', pitfall: 'The key distinction is that a WBS states what must be produced. A schedule states when, a budget states how much it costs, and a risk register records what may obstruct the work.' },
    { core: 'WBSは成果物と作業全体を階層的に分解したものです。', method: 'WBS（Work Breakdown Structure）は、最終成果物から始めてプロジェクト全体の範囲を管理可能なワークパッケージまで段階的に分解します。これにより作業の漏れを確認し、責任を割り当て、各パッケージの工数・費用・期間を見積もれます。', example: 'Webサイトなら、まず設計・開発・コンテンツに分け、開発を認証・商品一覧・決済へ分解します。最下位のパッケージは担当者と完了条件を明確にできる大きさにします。', pitfall: 'WBSは「何を作るか」を示します。日程は「いつ」、予算は「いくら」、リスク台帳は「何が妨げるか」を扱います。' }),
  'ip-roe': L(
    { core: 'ROE — Return on Equity, рентабельность собственного капитала.', method: 'Разделите чистую прибыль за период на средний собственный капитал и выразите результат в процентах.', example: 'Прибыль 12 млн и средний капитал 100 млн дают ROE = 12%.', pitfall: 'Высокий ROE может быть вызван не только эффективностью, но и малым капиталом из-за большого долга.' },
    { core: 'ROE means Return on Equity and measures return on owners’ capital.', method: 'Divide net income by average shareholders’ equity and express it as a percentage.', example: 'Net income 12 million / equity 100 million = 12% ROE.', pitfall: 'High ROE may also result from heavy debt reducing equity.' },
    { core: 'ROEは自己資本利益率（Return on Equity）です。', method: '当期純利益を平均自己資本で割り、百分率で表します。', example: '利益1,200万円÷平均自己資本1億円＝ROE 12%です。', pitfall: '高いROEは効率だけでなく、負債が多く自己資本が小さい場合にも生じます。' }),
  'fe-a-cache-hit': L(
    { core: 'Среднее время — математическое ожидание времени разных сценариев.', method: 'Умножьте время каждого сценария на его вероятность и сложите результаты.', example: '0,9×10 нс + 0,1×100 нс = 19 нс.', pitfall: 'Проверьте условие: иногда время проверки кэша при промахе нужно прибавлять, иногда уже учтено полное время.' },
    { core: 'Average access time is the expected value across possible scenarios.', method: 'Multiply each scenario time by its probability, then add the products.', example: '0.9×10 ns + 0.1×100 ns = 19 ns.', pitfall: 'Check whether miss time already includes the cache lookup; problems define this differently.' },
    { core: '平均アクセス時間は各シナリオの時間の期待値です。', method: '各時間に発生確率を掛け、その積を合計します。', example: '0.9×10ns + 0.1×100ns = 19nsです。', pitfall: 'ミス時間にキャッシュ確認時間が含まれるかを問題文で確認します。' }),
  'fe-a-normalization': L(
    { core: 'Нормализация хранит каждый факт в подходящем отношении и уменьшает избыточность.', method: 'Найдите зависимости атрибутов, выделите сущности и свяжите таблицы ключами.', example: 'Имя клиента не дублируют в каждой строке заказа: заказ хранит customer_id.', pitfall: 'Нормализация улучшает целостность, но не является шифрованием и не гарантирует максимальную скорость чтения.' },
    { core: 'Normalization stores each fact in an appropriate relation and reduces redundancy.', method: 'Identify dependencies, separate entities and connect tables with keys.', example: 'An order stores customer_id instead of repeating the customer name in every row.', pitfall: 'Normalization improves integrity; it is not encryption and may require joins.' },
    { core: '正規化は各事実を適切な関係に保存し、冗長性を減らします。', method: '属性間の依存関係を見つけ、実体を分け、キーで表を関連付けます。', example: '注文ごとに顧客名を重複させず、customer_idを保存します。', pitfall: '正規化は整合性を高めますが、暗号化ではなく、結合が必要になる場合があります。' }),
  'fe-b-complexity': L(
    { core: 'Big O показывает скорость роста работы при увеличении входа, игнорируя постоянные множители.', method: 'Последовательные блоки складывайте и оставляйте доминирующий порядок; вложенные циклы обычно перемножайте.', example: 'Два последовательных прохода: n+n=2n, поэтому O(n). Два вложенных прохода: n×n=O(n²).', pitfall: 'Количество циклов само по себе не означает степень: важно, вложены они или выполняются последовательно.' },
    { core: 'Big O describes growth as input size increases and ignores constant factors.', method: 'Add sequential blocks and keep the dominant term; multiply nested loop costs.', example: 'Two sequential scans: n+n=2n → O(n). Two nested scans: n×n → O(n²).', pitfall: 'Two loops are not automatically quadratic; nesting matters.' },
    { core: 'Big Oは入力サイズに対する処理量の増え方を表し、定数倍を無視します。', method: '連続処理は加算して支配項を残し、入れ子のループは通常乗算します。', example: '連続する2走査はn+n=2n→O(n)、二重ループはn×n→O(n²)です。', pitfall: 'ループが2個あるだけでO(n²)とは限りません。入れ子かどうかが重要です。' }),
  'fe-b-security': L(
    { core: 'Пароли хранят через медленную KDF и уникальную случайную соль.', method: 'Выберите Argon2id, scrypt, bcrypt или PBKDF2; настройте стоимость и храните соль рядом с хешем.', example: 'Одинаковые пароли с разными солями дают разные результаты, поэтому готовые таблицы не масштабируются на всю базу.', pitfall: 'Base64 — кодирование, не защита. Быстрый SHA без соли позволяет очень быстрый массовый перебор.' },
    { core: 'Passwords should use a slow KDF and a unique random salt.', method: 'Use Argon2id, scrypt, bcrypt or PBKDF2, tune the cost, and store the salt beside the hash.', example: 'Different salts make identical passwords produce different stored values.', pitfall: 'Base64 is encoding, not protection; a fast unsalted hash enables cheap bulk guessing.' },
    { core: 'パスワードは低速なKDFと一意のランダムソルトで保存します。', method: 'Argon2id、scrypt、bcrypt、PBKDF2などを使い、コストを調整し、ソルトをハッシュと共に保存します。', example: 'ソルトが異なれば同じパスワードでも保存値が異なり、事前計算表を使い回せません。', pitfall: 'Base64は符号化であり保護ではありません。高速なソルトなしハッシュは総当たりに弱いです。' }),
  'fe-b-stack': L(
    { core: 'Стек работает по принципу LIFO: последним вошёл — первым вышел.', method: 'Добавляйте push и удаляйте pop с одной вершины. Просмотр вершины обычно называется peek.', example: 'Вызовы функций помещаются в стек; завершившаяся последней вызванная функция снимается первой.', pitfall: 'В очереди добавление и удаление происходят с разных концов, поэтому она реализует FIFO.' },
    { core: 'A stack follows LIFO: last in, first out.', method: 'push adds to the top, pop removes from the top, and peek reads the top.', example: 'Function calls use a stack: the most recently called function returns first.', pitfall: 'A queue uses opposite ends and follows FIFO.' },
    { core: 'スタックはLIFO（後入れ先出し）です。', method: 'pushで頂上に追加し、popで頂上から取り出し、peekで頂上を参照します。', example: '関数呼出しでは最後に呼ばれた関数が最初に戻ります。', pitfall: 'キューは異なる端で追加・削除し、FIFOです。' }),
  'fe-a-tcp': L(
    { core: 'TCP создаёт соединение и предоставляет надёжный упорядоченный поток байтов.', method: 'Ищите признаки: подтверждения, номера последовательности, повторная передача и управление потоком.', example: 'Потерянный сегмент передаётся повторно, а получатель собирает байты в правильном порядке.', pitfall: 'TCP не гарантирует меньшую задержку. UDP легче, но надёжность при необходимости реализует приложение.' },
    { core: 'TCP establishes a connection and provides a reliable, ordered byte stream.', method: 'Look for acknowledgements, sequence numbers, retransmission and flow control.', example: 'A lost segment is retransmitted and received bytes are reordered correctly.', pitfall: 'TCP does not guarantee lower latency; UDP is lighter but leaves reliability to the application.' },
    { core: 'TCPはコネクションを確立し、信頼性のある順序付きバイトストリームを提供します。', method: '確認応答、シーケンス番号、再送、フロー制御が手掛かりです。', example: '失われたセグメントは再送され、受信側で正しい順序に並べられます。', pitfall: 'TCPが常に低遅延とは限りません。UDPの信頼性は必要に応じてアプリ側で実装します。' }),
};
