'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowDown,Search} from 'lucide-react';
import index from '../data/roadmap-index.json';
import {roadmapStages,roadmapTopics,type RoadmapLanguage} from '../lib/roadmap-topics';
import {ROADMAP_STORAGE_KEY,readRoadmapProgress,serializeRoadmapProgress,updateRoadmapProgress} from '../lib/roadmap-progress';
const validIds=new Set(index.topics.map(t=>t.id));
function CheckBox({checked,mixed,onChange,label,disabled}:{checked:boolean;mixed?:boolean;onChange:(v:boolean)=>void;label:string;disabled:boolean}){
 const ref=useRef<HTMLInputElement>(null);useEffect(()=>{if(ref.current)ref.current.indeterminate=!!mixed;},[mixed]);
 return <input ref={ref} type="checkbox" className="mt-1 size-5 shrink-0 cursor-pointer accent-teal-700" checked={checked} disabled={disabled} aria-label={label} onChange={e=>onChange(e.target.checked)}/>;
}
export default function StudyRoadmap({language,onLanguage,onExit}:{language:RoadmapLanguage;onLanguage:(l:RoadmapLanguage)=>void;onExit:()=>void}){
 const l=(ru:string,en:string,ja:string)=>({ru,en,ja})[language];
 const [progress,setProgress]=useState<Record<string,true>>({}),[ready,setReady]=useState(false),[error,setError]=useState(false);
 const [query,setQuery]=useState(''),[system,setSystem]=useState('all'),[level,setLevel]=useState('all'),[status,setStatus]=useState('all');
 useEffect(()=>{const sync=()=>{try{setProgress(readRoadmapProgress(localStorage.getItem(ROADMAP_STORAGE_KEY),validIds));}catch{setError(true);}setReady(true);};sync();const listener=(e:StorageEvent)=>{if(e.key===ROADMAP_STORAGE_KEY||e.key===null)sync();};window.addEventListener('storage',listener);return()=>window.removeEventListener('storage',listener);},[]);
 function mark(ids:string[],checked:boolean){let current=progress;if(!error){try{current=readRoadmapProgress(localStorage.getItem(ROADMAP_STORAGE_KEY),validIds);}catch{setError(true);}}const next=updateRoadmapProgress(current,ids,checked);setProgress(next);try{localStorage.setItem(ROADMAP_STORAGE_KEY,serializeRoadmapProgress(next));setError(false);}catch{setError(true);}}
 const visible=useMemo(()=>index.topics.filter(topic=>{
  const group=roadmapTopics.find(g=>g.id===topic.group)!;
  const text=[topic.ru,topic.en,topic.ja,group[language][0]].join(' ').normalize('NFKC').toLowerCase();
  return text.includes(query.trim().normalize('NFKC').toLowerCase())&&topic.refs.some(r=>(system==='all'||r.system===system)&&(level==='all'||r.level===level))&&(status==='all'||(status==='done'?!!progress[topic.id]:!progress[topic.id]));
 }),[query,system,level,status,progress,language]);
 const doneLabel=l('Изучено','Studied','学習済み'),detailsLabel=l('Подтемы и формулировки','Subtopics and search phrases','関連テーマ・検索語');
 return <main lang={language} className="min-h-screen bg-background text-foreground">
  <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-4"><button onClick={onExit} className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="size-4"/>{l('К экзаменам','Back to exams','試験へ戻る')}</button><div className="global-language-switch" aria-label="Interface language">{(['ru','en','ja'] as const).map(lang=><button key={lang} onClick={()=>onLanguage(lang)} className={lang===language?'active':''}>{lang==='ja'?'日本語':lang.toUpperCase()}</button>)}</div></div></header>
  <section className="mx-auto max-w-6xl px-5 pt-10 pb-8"><p className="text-xs font-bold tracking-widest text-primary">KISO / {l('РЕЖИМ ИЗУЧЕНИЯ','STUDY MODE','学習モード')}</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">{l('Роадмап','Roadmap','ロードマップ')}</h1><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">{l('От основ к уверенной практике. Идите по линии или выбирайте нужный блок — порядок рекомендательный, темы не заблокированы.','From foundations to confident practice. Follow the line or choose a block — the order is a recommendation, not a lock.','基礎から実践へ。線に沿って進んでも、必要な分野を選んでも構いません。順序は推奨で、項目はロックされません。')}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{l('Темы всех экзаменов в Kiso. Это учебный маршрут, а не официальный syllabus и не весь закрытый банк CBT.','Topics from every exam in Kiso. A study route, not an official syllabus or the entire private CBT bank.','Kisoに収録した全試験のテーマです。公式シラバスや非公開CBT問題全体ではなく、学習の道筋です。')}</p>
   <div className="mt-6 rounded-2xl border bg-card p-5"><div className="flex flex-wrap justify-between gap-3 text-sm"><strong>{doneLabel}: {Object.keys(progress).length}/{index.topics.length}</strong><span>{index.questionCount} {l('вопросов','questions','問')} · {index.packCount} {l('наборов','collections','問題集')}</span></div><progress aria-label={doneLabel} className="mt-3 h-2 w-full accent-teal-700" max={index.topics.length} value={Object.keys(progress).length}/><p className="mt-3 text-xs leading-5 text-muted-foreground">{l('Чекбоксы — ваша самооценка. Сохраняются только в этом браузере и не меняют результаты экзаменов.','Checkboxes are your self-assessment. Saved only in this browser; exam results stay unchanged.','チェックは自己評価です。このブラウザだけに保存され、試験結果は変わりません。')}</p>{error&&<p role="alert" className="mt-2 text-sm text-amber-700">{l('Не удалось сохранить отметки. Пока они доступны только на этой странице.','Could not save progress. Changes are available on this page only.','保存できませんでした。変更はこのページ内のみで有効です。')}</p>}</div>
   <div className="mt-6 flex flex-wrap gap-3"><label className="flex min-w-0 flex-[2_1_260px] items-center gap-2 rounded-xl border bg-card px-3"><Search className="size-4 shrink-0 text-muted-foreground"/><input aria-label={l('Найти тему','Find a topic','テーマを検索')} placeholder={l('Найти тему: двоичная, WBS, SQL…','Find a topic: binary, WBS, SQL…','テーマを検索：2進数、WBS、SQL…')} value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 w-full bg-transparent py-3 outline-none"/></label><select aria-label="ITPEC / IPA" value={system} onChange={e=>setSystem(e.target.value)} className="rounded-xl border bg-card px-3 py-3"><option value="all">ITPEC + IPA</option><option>ITPEC</option><option>IPA</option></select><select aria-label="IP / FE" value={level} onChange={e=>setLevel(e.target.value)} className="rounded-xl border bg-card px-3 py-3"><option value="all">IP + FE</option><option>IP</option><option>FE</option></select><select aria-label={doneLabel} value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border bg-card px-3 py-3"><option value="all">{l('Все','All','すべて')}</option><option value="remaining">{l('Не изучено','Not studied','未学習')}</option><option value="done">{doneLabel}</option></select></div>
   <div className="mt-3 flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>{visible.length} {l('подтем и формулировок','subtopics and phrases','項目・検索語')}</span><button className="text-primary underline" onClick={()=>{setQuery('');setSystem('all');setLevel('all');setStatus('all');}}>{l('Сбросить фильтры','Clear filters','条件をクリア')}</button></div><p className="mt-5 rounded-xl bg-primary/5 p-4 text-sm leading-6">{l('Пока здесь карта тем и краткие описания. Материалы добавим позже. Одинаковые формулировки объединены; близкие сохранены внутри общих блоков, чтобы не потерять детали.','For now: a topic map and short descriptions; materials will follow. Identical phrases are merged; related phrases remain within shared blocks to preserve detail.','現在はテーマと短い説明のみです。教材は後から追加します。同じ表現はまとめ、近い表現は論点を失わないよう同じ分野に残しています。')}</p>
  </section>
  <div className="mx-auto max-w-6xl px-5 pb-12">{!visible.length&&<p role="status" className="py-12 text-center">{l('Темы не найдены.','No topics found.','該当するテーマはありません。')}</p>}
   {roadmapStages.map((stage,i)=>{const groups=roadmapTopics.filter(g=>g.stage===i&&visible.some(s=>s.group===g.id));if(!groups.length)return null;return <section key={i} className="roadmap-stage relative pb-10" aria-labelledby={'stage-'+i}><h2 id={'stage-'+i} className="relative z-10 mb-6 flex items-center gap-3 text-xl font-bold"><span className="flex size-11 shrink-0 items-center justify-center rounded-full border-4 border-background bg-primary text-sm text-primary-foreground">{String(i+1).padStart(2,'0')}</span><span className="rounded-lg bg-background py-2 pr-3">{stage[language==='ru'?0:language==='en'?1:2]}</span></h2><div className="ml-[21px] grid gap-5 border-l-2 border-primary/20 pl-7 md:grid-cols-2 md:gap-x-10">{groups.map(group=>{
    const all=index.topics.filter(s=>s.group===group.id),items=visible.filter(s=>s.group===group.id),done=all.filter(s=>progress[s.id]).length;const markLabel=l('Отметить весь блок','Mark the entire block','ブロック全体を学習済みにする');
    return <article key={group.id} className="roadmap-card relative min-w-0 rounded-2xl border bg-card p-5 shadow-sm" data-topic={group.id}><div className="flex items-start justify-between gap-4"><h3 className="text-lg font-bold leading-6">{group[language][0]}</h3><CheckBox checked={done===all.length} mixed={done>0&&done<all.length} disabled={!ready} label={markLabel+': '+group[language][0]} onChange={v=>mark(all.map(s=>s.id),v)}/></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{group[language][1]}</p><p className="mt-3 text-xs font-semibold text-primary">{doneLabel}: {done}/{all.length} · {markLabel}</p>
     <details className="mt-4 border-t pt-3" open={query.trim()?true:undefined}><summary className="cursor-pointer text-sm font-semibold">{detailsLabel} ({items.length})</summary><div className="mt-3 max-h-96 space-y-3 overflow-y-auto pr-2">{items.map(sub=><div key={sub.id} className="rounded-lg border p-3"><label className="flex cursor-pointer items-start gap-3"><CheckBox checked={!!progress[sub.id]} disabled={!ready} label={sub[language]} onChange={v=>mark([sub.id],v)}/><span className={'min-w-0 break-words text-sm leading-6 '+(progress[sub.id]?'text-muted-foreground line-through':'')}>{sub[language]}</span></label><details className="mt-2 pl-8 text-xs text-muted-foreground"><summary className="cursor-pointer">{l('Встречается в экзаменах','Appears in exams','出題元')} ({sub.refs.length})</summary><ul className="mt-2 space-y-1">{sub.refs.map(r=><li key={r.pack+':'+r.question}>{r.system} {r.level} · {r.year}{r.pack.endsWith('autumn')?' · 10':r.pack.endsWith('spring')?' · 04':''}{r.pack.endsWith('sample')?' · 2022 sample':''} · {'part' in r?r.part:'Q'}{r.number}</li>)}</ul></details></div>)}</div></details>
    </article>;
   })}</div></section>;})}
   {!!visible.length&&<div className="ml-2 flex items-center gap-4 text-primary"><ArrowDown className="size-7"/><button onClick={onExit} className="font-semibold underline underline-offset-4">{l('Дальше — практика на экзаменах','Continue with exam practice','次は試験問題で練習')}</button></div>}
  </div><style>{`.roadmap-stage::before{content:'';position:absolute;left:21px;top:20px;bottom:0;width:2px;background:color-mix(in srgb,var(--primary) 25%,transparent)}.roadmap-card::before{content:'';position:absolute;left:-29px;top:29px;width:28px;height:2px;background:color-mix(in srgb,var(--primary) 30%,transparent)}@media(min-width:768px){.roadmap-card:nth-child(even)::before{left:-41px;width:40px}}`}</style>
 </main>;
}
